// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "AI-powered bulk CV screening \u0026 scoring platform API for B2B enterprises in Southeast Asia.",
        "title": "Azzet API",
        "termsOfService": "https://Azzet.ai/terms",
        "contact": {
            "name": "Azzet Support",
            "email": "support@Azzet.ai"
        },
        "license": {
            "name": "Proprietary",
            "url": "https://Azzet.ai/license"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/api/v1",
    "schemes": ["http", "https"],
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the health status of the API server",
                "tags": ["system"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-01-01T00:00:00Z"
                },
                "go_version": {
                    "type": "string",
                    "example": "go1.26.2"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT token authentication"
        },
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header",
            "description": "API key authentication"
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Azzet API",
	Description:      "AI-powered bulk CV screening & scoring platform API for B2B enterprises in Southeast Asia.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
