// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounting.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAccountsByWorkspace = `-- name: CountAccountsByWorkspace :one
SELECT COUNT(*) FROM accounts WHERE workspace_id = $1
`

func (q *Queries) CountAccountsByWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByWorkspace = `-- name: CountItemsByWorkspace :one
SELECT COUNT(*) FROM items WHERE workspace_id = $1 AND is_active = true
`

func (q *Queries) CountItemsByWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByWorkspace = `-- name: CountTransactionsByWorkspace :one
SELECT COUNT(*) FROM transactions WHERE workspace_id = $1
`

func (q *Queries) CountTransactionsByWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, workspace_id, parent_id, code, name, account_type, normal_balance, level, is_system, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, workspace_id, parent_id, code, name, account_type, normal_balance, level, is_system, is_active, created_at, updated_at
`

type CreateAccountParams struct {
	ID            uuid.UUID   `json:"id"`
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	AccountType   string      `json:"account_type"`
	NormalBalance string      `json:"normal_balance"`
	Level         int32       `json:"level"`
	IsSystem      bool        `json:"is_system"`
	IsActive      bool        `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

// ============================================================
// ACCOUNTS (Chart of Accounts)
// ============================================================
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.AccountType,
		arg.NormalBalance,
		arg.Level,
		arg.IsSystem,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.NormalBalance,
		&i.Level,
		&i.IsSystem,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one

INSERT INTO items (id, workspace_id, name, item_type, unit, unit_price, account_id, description, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, name, item_type, unit, unit_price, account_id, description, is_active, created_at, updated_at
`

type CreateItemParams struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Name        string         `json:"name"`
	ItemType    string         `json:"item_type"`
	Unit        string         `json:"unit"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	AccountID   pgtype.UUID    `json:"account_id"`
	Description pgtype.Text    `json:"description"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// ============================================================
// ITEMS
// ============================================================
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ItemType,
		arg.Unit,
		arg.UnitPrice,
		arg.AccountID,
		arg.Description,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ItemType,
		&i.Unit,
		&i.UnitPrice,
		&i.AccountID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one

INSERT INTO journal_entries (id, transaction_id, workspace_id, account_id, description, debit, credit, sort_order, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, transaction_id, workspace_id, account_id, description, debit, credit, sort_order, created_at
`

type CreateJournalEntryParams struct {
	ID            uuid.UUID      `json:"id"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Description   pgtype.Text    `json:"description"`
	Debit         pgtype.Numeric `json:"debit"`
	Credit        pgtype.Numeric `json:"credit"`
	SortOrder     int32          `json:"sort_order"`
	CreatedAt     time.Time      `json:"created_at"`
}

// ============================================================
// JOURNAL ENTRIES
// ============================================================
func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.ID,
		arg.TransactionID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Description,
		arg.Debit,
		arg.Credit,
		arg.SortOrder,
		arg.CreatedAt,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Description,
		&i.Debit,
		&i.Credit,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one

INSERT INTO ledger_entries (id, workspace_id, account_id, journal_entry_id, transaction_id, transaction_date, debit, credit, running_balance, posted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, account_id, journal_entry_id, transaction_id, transaction_date, debit, credit, running_balance, posted_at
`

type CreateLedgerEntryParams struct {
	ID              uuid.UUID      `json:"id"`
	WorkspaceID     uuid.UUID      `json:"workspace_id"`
	AccountID       uuid.UUID      `json:"account_id"`
	JournalEntryID  uuid.UUID      `json:"journal_entry_id"`
	TransactionID   uuid.UUID      `json:"transaction_id"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	Debit           pgtype.Numeric `json:"debit"`
	Credit          pgtype.Numeric `json:"credit"`
	RunningBalance  pgtype.Numeric `json:"running_balance"`
	PostedAt        time.Time      `json:"posted_at"`
}

// ============================================================
// LEDGER ENTRIES
// ============================================================
func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.JournalEntryID,
		arg.TransactionID,
		arg.TransactionDate,
		arg.Debit,
		arg.Credit,
		arg.RunningBalance,
		arg.PostedAt,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.JournalEntryID,
		&i.TransactionID,
		&i.TransactionDate,
		&i.Debit,
		&i.Credit,
		&i.RunningBalance,
		&i.PostedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
RETURNING id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, posted_at, voided_at, created_at, updated_at
`

type CreateTransactionParams struct {
	ID                    uuid.UUID      `json:"id"`
	WorkspaceID           uuid.UUID      `json:"workspace_id"`
	TransactionNumber     string         `json:"transaction_number"`
	TransactionType       string         `json:"transaction_type"`
	InputMode             string         `json:"input_mode"`
	Status                string         `json:"status"`
	CounterpartyEntityID  pgtype.UUID    `json:"counterparty_entity_id"`
	CounterpartyName      pgtype.Text    `json:"counterparty_name"`
	Description           pgtype.Text    `json:"description"`
	TransactionDate       pgtype.Date    `json:"transaction_date"`
	Amount                pgtype.Numeric `json:"amount"`
	Currency              string         `json:"currency"`
	Category              pgtype.Text    `json:"category"`
	AiConfidence          pgtype.Numeric `json:"ai_confidence"`
	PaymentMethod         pgtype.Text    `json:"payment_method"`
	IncludesTax           bool           `json:"includes_tax"`
	TaxAmount             pgtype.Numeric `json:"tax_amount"`
	ReversedTransactionID pgtype.UUID    `json:"reversed_transaction_id"`
	CreatedBy             uuid.UUID      `json:"created_by"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

// ============================================================
// TRANSACTIONS
// ============================================================
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.WorkspaceID,
		arg.TransactionNumber,
		arg.TransactionType,
		arg.InputMode,
		arg.Status,
		arg.CounterpartyEntityID,
		arg.CounterpartyName,
		arg.Description,
		arg.TransactionDate,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.AiConfidence,
		arg.PaymentMethod,
		arg.IncludesTax,
		arg.TaxAmount,
		arg.ReversedTransactionID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TransactionNumber,
		&i.TransactionType,
		&i.InputMode,
		&i.Status,
		&i.CounterpartyEntityID,
		&i.CounterpartyName,
		&i.Description,
		&i.TransactionDate,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.AiConfidence,
		&i.PaymentMethod,
		&i.IncludesTax,
		&i.TaxAmount,
		&i.ReversedTransactionID,
		&i.CreatedBy,
		&i.PostedAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionLineItem = `-- name: CreateTransactionLineItem :one

INSERT INTO transaction_line_items (id, transaction_id, workspace_id, item_id, description, quantity, unit, unit_price, discount_amount, tax_amount, line_total, sort_order, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, transaction_id, workspace_id, item_id, description, quantity, unit, unit_price, discount_amount, tax_amount, line_total, sort_order, created_at
`

type CreateTransactionLineItemParams struct {
	ID             uuid.UUID      `json:"id"`
	TransactionID  uuid.UUID      `json:"transaction_id"`
	WorkspaceID    uuid.UUID      `json:"workspace_id"`
	ItemID         pgtype.UUID    `json:"item_id"`
	Description    string         `json:"description"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	LineTotal      pgtype.Numeric `json:"line_total"`
	SortOrder      int32          `json:"sort_order"`
	CreatedAt      time.Time      `json:"created_at"`
}

// ============================================================
// TRANSACTION LINE ITEMS
// ============================================================
func (q *Queries) CreateTransactionLineItem(ctx context.Context, arg CreateTransactionLineItemParams) (TransactionLineItem, error) {
	row := q.db.QueryRow(ctx, createTransactionLineItem,
		arg.ID,
		arg.TransactionID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.DiscountAmount,
		arg.TaxAmount,
		arg.LineTotal,
		arg.SortOrder,
		arg.CreatedAt,
	)
	var i TransactionLineItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.WorkspaceID,
		&i.ItemID,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.LineTotal,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJournalEntriesByTransaction = `-- name: DeleteJournalEntriesByTransaction :exec
DELETE FROM journal_entries WHERE transaction_id = $1 AND workspace_id = $2
`

type DeleteJournalEntriesByTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteJournalEntriesByTransaction(ctx context.Context, arg DeleteJournalEntriesByTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteJournalEntriesByTransaction, arg.TransactionID, arg.WorkspaceID)
	return err
}

const deleteLineItemsByTransaction = `-- name: DeleteLineItemsByTransaction :exec
DELETE FROM transaction_line_items WHERE transaction_id = $1 AND workspace_id = $2
`

type DeleteLineItemsByTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteLineItemsByTransaction(ctx context.Context, arg DeleteLineItemsByTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteLineItemsByTransaction, arg.TransactionID, arg.WorkspaceID)
	return err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT workspace_id, account_id, period, total_debit, total_credit, ending_balance, transaction_count, updated_at FROM account_balances
WHERE workspace_id = $1 AND account_id = $2 AND period = $3
`

type GetAccountBalanceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
	Period      string    `json:"period"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (AccountBalance, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.WorkspaceID, arg.AccountID, arg.Period)
	var i AccountBalance
	err := row.Scan(
		&i.WorkspaceID,
		&i.AccountID,
		&i.Period,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.EndingBalance,
		&i.TransactionCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, workspace_id, parent_id, code, name, account_type, normal_balance, level, is_system, is_active, created_at, updated_at FROM accounts WHERE workspace_id = $1 AND code = $2
`

type GetAccountByCodeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Code        string    `json:"code"`
}

func (q *Queries) GetAccountByCode(ctx context.Context, arg GetAccountByCodeParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, arg.WorkspaceID, arg.Code)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.NormalBalance,
		&i.Level,
		&i.IsSystem,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, workspace_id, parent_id, code, name, account_type, normal_balance, level, is_system, is_active, created_at, updated_at FROM accounts WHERE id = $1 AND workspace_id = $2
`

type GetAccountByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.ID, arg.WorkspaceID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.NormalBalance,
		&i.Level,
		&i.IsSystem,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceSheet = `-- name: GetBalanceSheet :many
SELECT a.id, a.code, a.name, a.account_type, a.normal_balance,
    COALESCE(SUM(ab.ending_balance), 0) as balance
FROM accounts a
LEFT JOIN account_balances ab ON a.id = ab.account_id AND ab.workspace_id = $1 AND ab.period <= $2
WHERE a.workspace_id = $1 AND a.is_active = true AND a.account_type IN ('ASSET', 'LIABILITY', 'EQUITY')
GROUP BY a.id, a.code, a.name, a.account_type, a.normal_balance
HAVING COALESCE(SUM(ab.ending_balance), 0) != 0
ORDER BY a.code ASC
`

type GetBalanceSheetParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Period      string    `json:"period"`
}

type GetBalanceSheetRow struct {
	ID            uuid.UUID   `json:"id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	AccountType   string      `json:"account_type"`
	NormalBalance string      `json:"normal_balance"`
	Balance       interface{} `json:"balance"`
}

func (q *Queries) GetBalanceSheet(ctx context.Context, arg GetBalanceSheetParams) ([]GetBalanceSheetRow, error) {
	rows, err := q.db.Query(ctx, getBalanceSheet, arg.WorkspaceID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBalanceSheetRow{}
	for rows.Next() {
		var i GetBalanceSheetRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.NormalBalance,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashFlow = `-- name: GetCashFlow :many
SELECT le.transaction_date,
    COALESCE(SUM(le.debit), 0)::float8 as total_debit,
    COALESCE(SUM(le.credit), 0)::float8 as total_credit,
    (COALESCE(SUM(le.debit), 0) - COALESCE(SUM(le.credit), 0))::float8 as net_flow
FROM ledger_entries le
JOIN accounts a ON le.account_id = a.id
WHERE le.workspace_id = $1 AND a.code IN ('1-1001', '1-1002') AND le.transaction_date >= $2 AND le.transaction_date <= $3
GROUP BY le.transaction_date
ORDER BY le.transaction_date ASC
`

type GetCashFlowParams struct {
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetCashFlowRow struct {
	TransactionDate pgtype.Date `json:"transaction_date"`
	TotalDebit      float64     `json:"total_debit"`
	TotalCredit     float64     `json:"total_credit"`
	NetFlow         float64     `json:"net_flow"`
}

func (q *Queries) GetCashFlow(ctx context.Context, arg GetCashFlowParams) ([]GetCashFlowRow, error) {
	rows, err := q.db.Query(ctx, getCashFlow, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCashFlowRow{}
	for rows.Next() {
		var i GetCashFlowRow
		if err := rows.Scan(
			&i.TransactionDate,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.NetFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomeStatement = `-- name: GetIncomeStatement :many
SELECT a.id, a.code, a.name, a.account_type, a.normal_balance,
    COALESCE(SUM(ab.total_debit), 0) as total_debit,
    COALESCE(SUM(ab.total_credit), 0) as total_credit,
    COALESCE(SUM(ab.ending_balance), 0) as balance
FROM accounts a
LEFT JOIN account_balances ab ON a.id = ab.account_id AND ab.workspace_id = $1 AND ab.period >= $2 AND ab.period <= $3
WHERE a.workspace_id = $1 AND a.is_active = true AND a.account_type IN ('REVENUE', 'EXPENSE')
GROUP BY a.id, a.code, a.name, a.account_type, a.normal_balance
HAVING COALESCE(SUM(ab.ending_balance), 0) != 0
ORDER BY a.code ASC
`

type GetIncomeStatementParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Period      string    `json:"period"`
	Period_2    string    `json:"period_2"`
}

type GetIncomeStatementRow struct {
	ID            uuid.UUID   `json:"id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	AccountType   string      `json:"account_type"`
	NormalBalance string      `json:"normal_balance"`
	TotalDebit    interface{} `json:"total_debit"`
	TotalCredit   interface{} `json:"total_credit"`
	Balance       interface{} `json:"balance"`
}

func (q *Queries) GetIncomeStatement(ctx context.Context, arg GetIncomeStatementParams) ([]GetIncomeStatementRow, error) {
	rows, err := q.db.Query(ctx, getIncomeStatement, arg.WorkspaceID, arg.Period, arg.Period_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIncomeStatementRow{}
	for rows.Next() {
		var i GetIncomeStatementRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.NormalBalance,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, workspace_id, name, item_type, unit, unit_price, account_id, description, is_active, created_at, updated_at FROM items WHERE id = $1 AND workspace_id = $2
`

type GetItemByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetItemByID(ctx context.Context, arg GetItemByIDParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, arg.ID, arg.WorkspaceID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ItemType,
		&i.Unit,
		&i.UnitPrice,
		&i.AccountID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalSumByTransaction = `-- name: GetJournalSumByTransaction :one
SELECT COALESCE(SUM(debit), 0) as total_debit, COALESCE(SUM(credit), 0) as total_credit
FROM journal_entries WHERE transaction_id = $1 AND workspace_id = $2
`

type GetJournalSumByTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

type GetJournalSumByTransactionRow struct {
	TotalDebit  interface{} `json:"total_debit"`
	TotalCredit interface{} `json:"total_credit"`
}

func (q *Queries) GetJournalSumByTransaction(ctx context.Context, arg GetJournalSumByTransactionParams) (GetJournalSumByTransactionRow, error) {
	row := q.db.QueryRow(ctx, getJournalSumByTransaction, arg.TransactionID, arg.WorkspaceID)
	var i GetJournalSumByTransactionRow
	err := row.Scan(&i.TotalDebit, &i.TotalCredit)
	return i, err
}

const getLastLedgerBalance = `-- name: GetLastLedgerBalance :one
SELECT running_balance FROM ledger_entries
WHERE workspace_id = $1 AND account_id = $2
ORDER BY posted_at DESC, id DESC
LIMIT 1
`

type GetLastLedgerBalanceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
}

func (q *Queries) GetLastLedgerBalance(ctx context.Context, arg GetLastLedgerBalanceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLastLedgerBalance, arg.WorkspaceID, arg.AccountID)
	var running_balance pgtype.Numeric
	err := row.Scan(&running_balance)
	return running_balance, err
}

const getNextTransactionNumber = `-- name: GetNextTransactionNumber :one
SELECT COALESCE(MAX(CAST(SUBSTRING(transaction_number FROM '[0-9]+$') AS INT)), 0) + 1 AS next_number
FROM transactions WHERE workspace_id = $1
`

func (q *Queries) GetNextTransactionNumber(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextTransactionNumber, workspaceID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, posted_at, voided_at, created_at, updated_at FROM transactions WHERE id = $1 AND workspace_id = $2
`

type GetTransactionByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.WorkspaceID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TransactionNumber,
		&i.TransactionType,
		&i.InputMode,
		&i.Status,
		&i.CounterpartyEntityID,
		&i.CounterpartyName,
		&i.Description,
		&i.TransactionDate,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.AiConfidence,
		&i.PaymentMethod,
		&i.IncludesTax,
		&i.TaxAmount,
		&i.ReversedTransactionID,
		&i.CreatedBy,
		&i.PostedAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrialBalance = `-- name: GetTrialBalance :many
SELECT a.id, a.code, a.name, a.account_type, a.normal_balance,
    COALESCE(SUM(ab.total_debit), 0) as total_debit,
    COALESCE(SUM(ab.total_credit), 0) as total_credit,
    COALESCE(SUM(ab.ending_balance), 0) as balance
FROM accounts a
LEFT JOIN account_balances ab ON a.id = ab.account_id AND ab.workspace_id = $1 AND ab.period >= $2 AND ab.period <= $3
WHERE a.workspace_id = $1 AND a.is_active = true
GROUP BY a.id, a.code, a.name, a.account_type, a.normal_balance
HAVING COALESCE(SUM(ab.total_debit), 0) > 0 OR COALESCE(SUM(ab.total_credit), 0) > 0
ORDER BY a.code ASC
`

type GetTrialBalanceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Period      string    `json:"period"`
	Period_2    string    `json:"period_2"`
}

type GetTrialBalanceRow struct {
	ID            uuid.UUID   `json:"id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	AccountType   string      `json:"account_type"`
	NormalBalance string      `json:"normal_balance"`
	TotalDebit    interface{} `json:"total_debit"`
	TotalCredit   interface{} `json:"total_credit"`
	Balance       interface{} `json:"balance"`
}

func (q *Queries) GetTrialBalance(ctx context.Context, arg GetTrialBalanceParams) ([]GetTrialBalanceRow, error) {
	rows, err := q.db.Query(ctx, getTrialBalance, arg.WorkspaceID, arg.Period, arg.Period_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrialBalanceRow{}
	for rows.Next() {
		var i GetTrialBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.NormalBalance,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountBalancesByDateRange = `-- name: ListAccountBalancesByDateRange :many
SELECT ab.workspace_id, ab.account_id, ab.period, ab.total_debit, ab.total_credit, ab.ending_balance, ab.transaction_count, ab.updated_at, a.code as account_code, a.name as account_name, a.account_type, a.normal_balance
FROM account_balances ab
JOIN accounts a ON ab.account_id = a.id
WHERE ab.workspace_id = $1 AND ab.period >= $2 AND ab.period <= $3
ORDER BY a.code ASC, ab.period ASC
`

type ListAccountBalancesByDateRangeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Period      string    `json:"period"`
	Period_2    string    `json:"period_2"`
}

type ListAccountBalancesByDateRangeRow struct {
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	AccountID        uuid.UUID      `json:"account_id"`
	Period           string         `json:"period"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
	EndingBalance    pgtype.Numeric `json:"ending_balance"`
	TransactionCount int32          `json:"transaction_count"`
	UpdatedAt        time.Time      `json:"updated_at"`
	AccountCode      string         `json:"account_code"`
	AccountName      string         `json:"account_name"`
	AccountType      string         `json:"account_type"`
	NormalBalance    string         `json:"normal_balance"`
}

func (q *Queries) ListAccountBalancesByDateRange(ctx context.Context, arg ListAccountBalancesByDateRangeParams) ([]ListAccountBalancesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalancesByDateRange, arg.WorkspaceID, arg.Period, arg.Period_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountBalancesByDateRangeRow{}
	for rows.Next() {
		var i ListAccountBalancesByDateRangeRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.AccountID,
			&i.Period,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.EndingBalance,
			&i.TransactionCount,
			&i.UpdatedAt,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountType,
			&i.NormalBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountBalancesByPeriod = `-- name: ListAccountBalancesByPeriod :many
SELECT ab.workspace_id, ab.account_id, ab.period, ab.total_debit, ab.total_credit, ab.ending_balance, ab.transaction_count, ab.updated_at, a.code as account_code, a.name as account_name, a.account_type, a.normal_balance
FROM account_balances ab
JOIN accounts a ON ab.account_id = a.id
WHERE ab.workspace_id = $1 AND ab.period = $2
ORDER BY a.code ASC
`

type ListAccountBalancesByPeriodParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Period      string    `json:"period"`
}

type ListAccountBalancesByPeriodRow struct {
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	AccountID        uuid.UUID      `json:"account_id"`
	Period           string         `json:"period"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
	EndingBalance    pgtype.Numeric `json:"ending_balance"`
	TransactionCount int32          `json:"transaction_count"`
	UpdatedAt        time.Time      `json:"updated_at"`
	AccountCode      string         `json:"account_code"`
	AccountName      string         `json:"account_name"`
	AccountType      string         `json:"account_type"`
	NormalBalance    string         `json:"normal_balance"`
}

func (q *Queries) ListAccountBalancesByPeriod(ctx context.Context, arg ListAccountBalancesByPeriodParams) ([]ListAccountBalancesByPeriodRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalancesByPeriod, arg.WorkspaceID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountBalancesByPeriodRow{}
	for rows.Next() {
		var i ListAccountBalancesByPeriodRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.AccountID,
			&i.Period,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.EndingBalance,
			&i.TransactionCount,
			&i.UpdatedAt,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountType,
			&i.NormalBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByType = `-- name: ListAccountsByType :many
SELECT id, workspace_id, parent_id, code, name, account_type, normal_balance, level, is_system, is_active, created_at, updated_at FROM accounts
WHERE workspace_id = $1 AND account_type = $2 AND is_active = true
ORDER BY code ASC
`

type ListAccountsByTypeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountType string    `json:"account_type"`
}

func (q *Queries) ListAccountsByType(ctx context.Context, arg ListAccountsByTypeParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByType, arg.WorkspaceID, arg.AccountType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.NormalBalance,
			&i.Level,
			&i.IsSystem,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByWorkspace = `-- name: ListAccountsByWorkspace :many
SELECT id, workspace_id, parent_id, code, name, account_type, normal_balance, level, is_system, is_active, created_at, updated_at FROM accounts
WHERE workspace_id = $1 AND is_active = true
ORDER BY code ASC
`

func (q *Queries) ListAccountsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.NormalBalance,
			&i.Level,
			&i.IsSystem,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccountsByWorkspace = `-- name: ListAllAccountsByWorkspace :many
SELECT id, workspace_id, parent_id, code, name, account_type, normal_balance, level, is_system, is_active, created_at, updated_at FROM accounts
WHERE workspace_id = $1
ORDER BY code ASC
`

func (q *Queries) ListAllAccountsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAllAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.NormalBalance,
			&i.Level,
			&i.IsSystem,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllItemsByWorkspace = `-- name: ListAllItemsByWorkspace :many
SELECT id, workspace_id, name, item_type, unit, unit_price, account_id, description, is_active, created_at, updated_at FROM items
WHERE workspace_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListAllItemsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListAllItemsByWorkspace(ctx context.Context, arg ListAllItemsByWorkspaceParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listAllItemsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ItemType,
			&i.Unit,
			&i.UnitPrice,
			&i.AccountID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByType = `-- name: ListItemsByType :many
SELECT id, workspace_id, name, item_type, unit, unit_price, account_id, description, is_active, created_at, updated_at FROM items
WHERE workspace_id = $1 AND item_type = $2 AND is_active = true
ORDER BY name ASC
LIMIT $3 OFFSET $4
`

type ListItemsByTypeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ItemType    string    `json:"item_type"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListItemsByType(ctx context.Context, arg ListItemsByTypeParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByType,
		arg.WorkspaceID,
		arg.ItemType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ItemType,
			&i.Unit,
			&i.UnitPrice,
			&i.AccountID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByWorkspace = `-- name: ListItemsByWorkspace :many
SELECT id, workspace_id, name, item_type, unit, unit_price, account_id, description, is_active, created_at, updated_at FROM items
WHERE workspace_id = $1 AND is_active = true
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListItemsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListItemsByWorkspace(ctx context.Context, arg ListItemsByWorkspaceParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ItemType,
			&i.Unit,
			&i.UnitPrice,
			&i.AccountID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByTransaction = `-- name: ListJournalEntriesByTransaction :many
SELECT je.id, je.transaction_id, je.workspace_id, je.account_id, je.description, je.debit, je.credit, je.sort_order, je.created_at, a.code as account_code, a.name as account_name
FROM journal_entries je
JOIN accounts a ON je.account_id = a.id
WHERE je.transaction_id = $1 AND je.workspace_id = $2
ORDER BY je.sort_order ASC
`

type ListJournalEntriesByTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

type ListJournalEntriesByTransactionRow struct {
	ID            uuid.UUID      `json:"id"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Description   pgtype.Text    `json:"description"`
	Debit         pgtype.Numeric `json:"debit"`
	Credit        pgtype.Numeric `json:"credit"`
	SortOrder     int32          `json:"sort_order"`
	CreatedAt     time.Time      `json:"created_at"`
	AccountCode   string         `json:"account_code"`
	AccountName   string         `json:"account_name"`
}

func (q *Queries) ListJournalEntriesByTransaction(ctx context.Context, arg ListJournalEntriesByTransactionParams) ([]ListJournalEntriesByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByTransaction, arg.TransactionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalEntriesByTransactionRow{}
	for rows.Next() {
		var i ListJournalEntriesByTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Description,
			&i.Debit,
			&i.Credit,
			&i.SortOrder,
			&i.CreatedAt,
			&i.AccountCode,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT le.id, le.workspace_id, le.account_id, le.journal_entry_id, le.transaction_id, le.transaction_date, le.debit, le.credit, le.running_balance, le.posted_at, t.transaction_number, t.description as tx_description
FROM ledger_entries le
JOIN transactions t ON le.transaction_id = t.id
WHERE le.workspace_id = $1 AND le.account_id = $2
ORDER BY le.posted_at DESC, le.id DESC
LIMIT $3 OFFSET $4
`

type ListLedgerEntriesByAccountParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListLedgerEntriesByAccountRow struct {
	ID                uuid.UUID      `json:"id"`
	WorkspaceID       uuid.UUID      `json:"workspace_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	JournalEntryID    uuid.UUID      `json:"journal_entry_id"`
	TransactionID     uuid.UUID      `json:"transaction_id"`
	TransactionDate   pgtype.Date    `json:"transaction_date"`
	Debit             pgtype.Numeric `json:"debit"`
	Credit            pgtype.Numeric `json:"credit"`
	RunningBalance    pgtype.Numeric `json:"running_balance"`
	PostedAt          time.Time      `json:"posted_at"`
	TransactionNumber string         `json:"transaction_number"`
	TxDescription     pgtype.Text    `json:"tx_description"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]ListLedgerEntriesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerEntriesByAccountRow{}
	for rows.Next() {
		var i ListLedgerEntriesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.JournalEntryID,
			&i.TransactionID,
			&i.TransactionDate,
			&i.Debit,
			&i.Credit,
			&i.RunningBalance,
			&i.PostedAt,
			&i.TransactionNumber,
			&i.TxDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByAccountDateRange = `-- name: ListLedgerEntriesByAccountDateRange :many
SELECT le.id, le.workspace_id, le.account_id, le.journal_entry_id, le.transaction_id, le.transaction_date, le.debit, le.credit, le.running_balance, le.posted_at, t.transaction_number, t.description as tx_description
FROM ledger_entries le
JOIN transactions t ON le.transaction_id = t.id
WHERE le.workspace_id = $1 AND le.account_id = $2 AND le.transaction_date >= $3 AND le.transaction_date <= $4
ORDER BY le.posted_at ASC, le.id ASC
`

type ListLedgerEntriesByAccountDateRangeParams struct {
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	AccountID         uuid.UUID   `json:"account_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type ListLedgerEntriesByAccountDateRangeRow struct {
	ID                uuid.UUID      `json:"id"`
	WorkspaceID       uuid.UUID      `json:"workspace_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	JournalEntryID    uuid.UUID      `json:"journal_entry_id"`
	TransactionID     uuid.UUID      `json:"transaction_id"`
	TransactionDate   pgtype.Date    `json:"transaction_date"`
	Debit             pgtype.Numeric `json:"debit"`
	Credit            pgtype.Numeric `json:"credit"`
	RunningBalance    pgtype.Numeric `json:"running_balance"`
	PostedAt          time.Time      `json:"posted_at"`
	TransactionNumber string         `json:"transaction_number"`
	TxDescription     pgtype.Text    `json:"tx_description"`
}

func (q *Queries) ListLedgerEntriesByAccountDateRange(ctx context.Context, arg ListLedgerEntriesByAccountDateRangeParams) ([]ListLedgerEntriesByAccountDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccountDateRange,
		arg.WorkspaceID,
		arg.AccountID,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerEntriesByAccountDateRangeRow{}
	for rows.Next() {
		var i ListLedgerEntriesByAccountDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.JournalEntryID,
			&i.TransactionID,
			&i.TransactionDate,
			&i.Debit,
			&i.Credit,
			&i.RunningBalance,
			&i.PostedAt,
			&i.TransactionNumber,
			&i.TxDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItemsByTransaction = `-- name: ListLineItemsByTransaction :many
SELECT id, transaction_id, workspace_id, item_id, description, quantity, unit, unit_price, discount_amount, tax_amount, line_total, sort_order, created_at FROM transaction_line_items
WHERE transaction_id = $1 AND workspace_id = $2
ORDER BY sort_order ASC
`

type ListLineItemsByTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListLineItemsByTransaction(ctx context.Context, arg ListLineItemsByTransactionParams) ([]TransactionLineItem, error) {
	rows, err := q.db.Query(ctx, listLineItemsByTransaction, arg.TransactionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionLineItem{}
	for rows.Next() {
		var i TransactionLineItem
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.WorkspaceID,
			&i.ItemID,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.LineTotal,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCounterparty = `-- name: ListTransactionsByCounterparty :many
SELECT id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, posted_at, voided_at, created_at, updated_at FROM transactions
WHERE workspace_id = $1 AND counterparty_entity_id = $2
ORDER BY transaction_date DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByCounterpartyParams struct {
	WorkspaceID          uuid.UUID   `json:"workspace_id"`
	CounterpartyEntityID pgtype.UUID `json:"counterparty_entity_id"`
	Limit                int32       `json:"limit"`
	Offset               int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByCounterparty(ctx context.Context, arg ListTransactionsByCounterpartyParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCounterparty,
		arg.WorkspaceID,
		arg.CounterpartyEntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TransactionNumber,
			&i.TransactionType,
			&i.InputMode,
			&i.Status,
			&i.CounterpartyEntityID,
			&i.CounterpartyName,
			&i.Description,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.AiConfidence,
			&i.PaymentMethod,
			&i.IncludesTax,
			&i.TaxAmount,
			&i.ReversedTransactionID,
			&i.CreatedBy,
			&i.PostedAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, posted_at, voided_at, created_at, updated_at FROM transactions
WHERE workspace_id = $1 AND transaction_date >= $2 AND transaction_date <= $3
ORDER BY transaction_date DESC, created_at DESC
LIMIT $4 OFFSET $5
`

type ListTransactionsByDateRangeParams struct {
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange,
		arg.WorkspaceID,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TransactionNumber,
			&i.TransactionType,
			&i.InputMode,
			&i.Status,
			&i.CounterpartyEntityID,
			&i.CounterpartyName,
			&i.Description,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.AiConfidence,
			&i.PaymentMethod,
			&i.IncludesTax,
			&i.TaxAmount,
			&i.ReversedTransactionID,
			&i.CreatedBy,
			&i.PostedAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByStatus = `-- name: ListTransactionsByStatus :many
SELECT id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, posted_at, voided_at, created_at, updated_at FROM transactions
WHERE workspace_id = $1 AND status = $2
ORDER BY transaction_date DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByStatusParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Status      string    `json:"status"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByStatus(ctx context.Context, arg ListTransactionsByStatusParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByStatus,
		arg.WorkspaceID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TransactionNumber,
			&i.TransactionType,
			&i.InputMode,
			&i.Status,
			&i.CounterpartyEntityID,
			&i.CounterpartyName,
			&i.Description,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.AiConfidence,
			&i.PaymentMethod,
			&i.IncludesTax,
			&i.TaxAmount,
			&i.ReversedTransactionID,
			&i.CreatedBy,
			&i.PostedAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, posted_at, voided_at, created_at, updated_at FROM transactions
WHERE workspace_id = $1 AND transaction_type = $2
ORDER BY transaction_date DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByTypeParams struct {
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	TransactionType string    `json:"transaction_type"`
	Limit           int32     `json:"limit"`
	Offset          int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByType,
		arg.WorkspaceID,
		arg.TransactionType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TransactionNumber,
			&i.TransactionType,
			&i.InputMode,
			&i.Status,
			&i.CounterpartyEntityID,
			&i.CounterpartyName,
			&i.Description,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.AiConfidence,
			&i.PaymentMethod,
			&i.IncludesTax,
			&i.TaxAmount,
			&i.ReversedTransactionID,
			&i.CreatedBy,
			&i.PostedAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByWorkspace = `-- name: ListTransactionsByWorkspace :many
SELECT id, workspace_id, transaction_number, transaction_type, input_mode, status, counterparty_entity_id, counterparty_name, description, transaction_date, amount, currency, category, ai_confidence, payment_method, includes_tax, tax_amount, reversed_transaction_id, created_by, posted_at, voided_at, created_at, updated_at FROM transactions
WHERE workspace_id = $1
ORDER BY transaction_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByWorkspace(ctx context.Context, arg ListTransactionsByWorkspaceParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TransactionNumber,
			&i.TransactionType,
			&i.InputMode,
			&i.Status,
			&i.CounterpartyEntityID,
			&i.CounterpartyName,
			&i.Description,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.AiConfidence,
			&i.PaymentMethod,
			&i.IncludesTax,
			&i.TaxAmount,
			&i.ReversedTransactionID,
			&i.CreatedBy,
			&i.PostedAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionFailed = `-- name: MarkTransactionFailed :exec
UPDATE transactions SET status = 'FAILED', updated_at = NOW() WHERE id = $1 AND workspace_id = $2
`

type MarkTransactionFailedParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) MarkTransactionFailed(ctx context.Context, arg MarkTransactionFailedParams) error {
	_, err := q.db.Exec(ctx, markTransactionFailed, arg.ID, arg.WorkspaceID)
	return err
}

const markTransactionPosted = `-- name: MarkTransactionPosted :exec
UPDATE transactions SET status = 'POSTED', posted_at = NOW(), updated_at = NOW() WHERE id = $1 AND workspace_id = $2
`

type MarkTransactionPostedParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) MarkTransactionPosted(ctx context.Context, arg MarkTransactionPostedParams) error {
	_, err := q.db.Exec(ctx, markTransactionPosted, arg.ID, arg.WorkspaceID)
	return err
}

const markTransactionVoid = `-- name: MarkTransactionVoid :exec
UPDATE transactions SET status = 'VOID', voided_at = NOW(), updated_at = NOW() WHERE id = $1 AND workspace_id = $2
`

type MarkTransactionVoidParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) MarkTransactionVoid(ctx context.Context, arg MarkTransactionVoidParams) error {
	_, err := q.db.Exec(ctx, markTransactionVoid, arg.ID, arg.WorkspaceID)
	return err
}

const reactivateItem = `-- name: ReactivateItem :exec
UPDATE items SET is_active = true, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type ReactivateItemParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ReactivateItem(ctx context.Context, arg ReactivateItemParams) error {
	_, err := q.db.Exec(ctx, reactivateItem, arg.ID, arg.WorkspaceID)
	return err
}

const softDeleteItem = `-- name: SoftDeleteItem :exec
UPDATE items SET is_active = false, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type SoftDeleteItemParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) error {
	_, err := q.db.Exec(ctx, softDeleteItem, arg.ID, arg.WorkspaceID)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET name = $3, parent_id = $4, is_active = $5, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND is_system = false
`

type UpdateAccountParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Name        string      `json:"name"`
	ParentID    pgtype.UUID `json:"parent_id"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ParentID,
		arg.IsActive,
	)
	return err
}

const updateDraftTransaction = `-- name: UpdateDraftTransaction :exec
UPDATE transactions SET description = $3, transaction_date = $4, amount = $5, category = $6, counterparty_entity_id = $7, counterparty_name = $8, payment_method = $9, includes_tax = $10, tax_amount = $11, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND status = 'DRAFT'
`

type UpdateDraftTransactionParams struct {
	ID                   uuid.UUID      `json:"id"`
	WorkspaceID          uuid.UUID      `json:"workspace_id"`
	Description          pgtype.Text    `json:"description"`
	TransactionDate      pgtype.Date    `json:"transaction_date"`
	Amount               pgtype.Numeric `json:"amount"`
	Category             pgtype.Text    `json:"category"`
	CounterpartyEntityID pgtype.UUID    `json:"counterparty_entity_id"`
	CounterpartyName     pgtype.Text    `json:"counterparty_name"`
	PaymentMethod        pgtype.Text    `json:"payment_method"`
	IncludesTax          bool           `json:"includes_tax"`
	TaxAmount            pgtype.Numeric `json:"tax_amount"`
}

func (q *Queries) UpdateDraftTransaction(ctx context.Context, arg UpdateDraftTransactionParams) error {
	_, err := q.db.Exec(ctx, updateDraftTransaction,
		arg.ID,
		arg.WorkspaceID,
		arg.Description,
		arg.TransactionDate,
		arg.Amount,
		arg.Category,
		arg.CounterpartyEntityID,
		arg.CounterpartyName,
		arg.PaymentMethod,
		arg.IncludesTax,
		arg.TaxAmount,
	)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items SET name = $3, item_type = $4, unit = $5, unit_price = $6, account_id = $7, description = $8, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type UpdateItemParams struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Name        string         `json:"name"`
	ItemType    string         `json:"item_type"`
	Unit        string         `json:"unit"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	AccountID   pgtype.UUID    `json:"account_id"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ItemType,
		arg.Unit,
		arg.UnitPrice,
		arg.AccountID,
		arg.Description,
	)
	return err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions SET status = $3, updated_at = NOW() WHERE id = $1 AND workspace_id = $2
`

type UpdateTransactionStatusParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.WorkspaceID, arg.Status)
	return err
}

const upsertAccountBalance = `-- name: UpsertAccountBalance :one

INSERT INTO account_balances (workspace_id, account_id, period, total_debit, total_credit, ending_balance, transaction_count, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, NOW())
ON CONFLICT (workspace_id, account_id, period)
DO UPDATE SET
    total_debit = account_balances.total_debit + EXCLUDED.total_debit,
    total_credit = account_balances.total_credit + EXCLUDED.total_credit,
    ending_balance = EXCLUDED.ending_balance,
    transaction_count = account_balances.transaction_count + 1,
    updated_at = NOW()
RETURNING workspace_id, account_id, period, total_debit, total_credit, ending_balance, transaction_count, updated_at
`

type UpsertAccountBalanceParams struct {
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Period        string         `json:"period"`
	TotalDebit    pgtype.Numeric `json:"total_debit"`
	TotalCredit   pgtype.Numeric `json:"total_credit"`
	EndingBalance pgtype.Numeric `json:"ending_balance"`
}

// ============================================================
// ACCOUNT BALANCES
// ============================================================
func (q *Queries) UpsertAccountBalance(ctx context.Context, arg UpsertAccountBalanceParams) (AccountBalance, error) {
	row := q.db.QueryRow(ctx, upsertAccountBalance,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Period,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.EndingBalance,
	)
	var i AccountBalance
	err := row.Scan(
		&i.WorkspaceID,
		&i.AccountID,
		&i.Period,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.EndingBalance,
		&i.TransactionCount,
		&i.UpdatedAt,
	)
	return i, err
}
