// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO platform_admins (id, email, password_hash, name, role, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, password_hash, name, role, mfa_secret, mfa_enabled, status, last_login_at, last_login_ip, created_at, updated_at
`

type CreateAdminParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Role         string    `json:"role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
UPDATE platform_admins SET status = 'DELETED', updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const existsAdminByEmail = `-- name: ExistsAdminByEmail :one
SELECT EXISTS(SELECT 1 FROM platform_admins WHERE email = $1)
`

func (q *Queries) ExistsAdminByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsAdminByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, name, role, mfa_secret, mfa_enabled, status, last_login_at, last_login_ip, created_at, updated_at FROM platform_admins WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, name, role, mfa_secret, mfa_enabled, status, last_login_at, last_login_ip, created_at, updated_at FROM platform_admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, password_hash, name, role, mfa_secret, mfa_enabled, status, last_login_at, last_login_ip, created_at, updated_at FROM platform_admins WHERE status != 'DELETED' ORDER BY created_at DESC
`

func (q *Queries) ListAdmins(ctx context.Context) ([]PlatformAdmin, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAdmin{}
	for rows.Next() {
		var i PlatformAdmin
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.MfaSecret,
			&i.MfaEnabled,
			&i.Status,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmin = `-- name: UpdateAdmin :exec
UPDATE platform_admins
SET name = $2, role = $3, status = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Role   string    `json:"role"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) error {
	_, err := q.db.Exec(ctx, updateAdmin,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Status,
	)
	return err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE platform_admins SET last_login_at = NOW(), last_login_ip = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAdminLastLoginParams struct {
	ID          uuid.UUID   `json:"id"`
	LastLoginIp *netip.Addr `json:"last_login_ip"`
}

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, arg UpdateAdminLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, arg.ID, arg.LastLoginIp)
	return err
}

const updateAdminMFA = `-- name: UpdateAdminMFA :exec
UPDATE platform_admins SET mfa_secret = $2, mfa_enabled = $3, updated_at = NOW() WHERE id = $1
`

type UpdateAdminMFAParams struct {
	ID         uuid.UUID   `json:"id"`
	MfaSecret  pgtype.Text `json:"mfa_secret"`
	MfaEnabled bool        `json:"mfa_enabled"`
}

func (q *Queries) UpdateAdminMFA(ctx context.Context, arg UpdateAdminMFAParams) error {
	_, err := q.db.Exec(ctx, updateAdminMFA, arg.ID, arg.MfaSecret, arg.MfaEnabled)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE platform_admins SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}
