// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, user_id, event_type, event_data, ip_address, user_agent, success, error_message, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAuditLogParams struct {
	ID           uuid.UUID   `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	EventType    string      `json:"event_type"`
	EventData    []byte      `json:"event_data"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Success      bool        `json:"success"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.EventType,
		arg.EventData,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	return err
}

const createOTP = `-- name: CreateOTP :exec
INSERT INTO otp_codes (id, identifier, identifier_type, code, purpose, attempts, max_attempts, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, 0, $6, $7, $8)
`

type CreateOTPParams struct {
	ID             uuid.UUID `json:"id"`
	Identifier     string    `json:"identifier"`
	IdentifierType string    `json:"identifier_type"`
	Code           string    `json:"code"`
	Purpose        string    `json:"purpose"`
	MaxAttempts    int32     `json:"max_attempts"`
	ExpiresAt      time.Time `json:"expires_at"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) error {
	_, err := q.db.Exec(ctx, createOTP,
		arg.ID,
		arg.Identifier,
		arg.IdentifierType,
		arg.Code,
		arg.Purpose,
		arg.MaxAttempts,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, refresh_token, device_name, device_type, ip_address, user_agent, expires_at, last_used_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, refresh_token, device_name, device_type, ip_address, user_agent, expires_at, last_used_at, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	RefreshToken string      `json:"refresh_token"`
	DeviceName   pgtype.Text `json:"device_name"`
	DeviceType   pgtype.Text `json:"device_type"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	ExpiresAt    time.Time   `json:"expires_at"`
	LastUsedAt   time.Time   `json:"last_used_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.DeviceName,
		arg.DeviceType,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.DeviceName,
		&i.DeviceType,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, whatsapp, password_hash, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, whatsapp, password_hash, email_verified, whatsapp_verified, status, last_login_at, last_login_ip, created_at, updated_at, name
`

type CreateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        pgtype.Text `json:"email"`
	Whatsapp     pgtype.Text `json:"whatsapp"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Whatsapp,
		arg.PasswordHash,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Whatsapp,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.WhatsappVerified,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otp_codes WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const deleteSessionByRefreshToken = `-- name: DeleteSessionByRefreshToken :exec
DELETE FROM sessions WHERE refresh_token = $1
`

func (q *Queries) DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, deleteSessionByRefreshToken, refreshToken)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) ExistsByEmail(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByWhatsApp = `-- name: ExistsByWhatsApp :one
SELECT EXISTS(SELECT 1 FROM users WHERE whatsapp = $1)
`

func (q *Queries) ExistsByWhatsApp(ctx context.Context, whatsapp pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsByWhatsApp, whatsapp)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token, device_name, device_type, ip_address, user_agent, expires_at, last_used_at, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.DeviceName,
		&i.DeviceType,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, device_name, device_type, ip_address, user_agent, expires_at, last_used_at, created_at FROM sessions WHERE refresh_token = $1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.DeviceName,
		&i.DeviceType,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, whatsapp, password_hash, email_verified, whatsapp_verified, status, last_login_at, last_login_ip, created_at, updated_at, name FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Whatsapp,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.WhatsappVerified,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, whatsapp, password_hash, email_verified, whatsapp_verified, status, last_login_at, last_login_ip, created_at, updated_at, name FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Whatsapp,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.WhatsappVerified,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getUserByWhatsApp = `-- name: GetUserByWhatsApp :one
SELECT id, email, whatsapp, password_hash, email_verified, whatsapp_verified, status, last_login_at, last_login_ip, created_at, updated_at, name FROM users WHERE whatsapp = $1
`

func (q *Queries) GetUserByWhatsApp(ctx context.Context, whatsapp pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWhatsApp, whatsapp)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Whatsapp,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.WhatsappVerified,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, refresh_token, device_name, device_type, ip_address, user_agent, expires_at, last_used_at, created_at FROM sessions
WHERE user_id = $1 AND expires_at > NOW()
ORDER BY last_used_at DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshToken,
			&i.DeviceName,
			&i.DeviceType,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, identifier, identifier_type, code, purpose, attempts, max_attempts, expires_at, used_at, created_at FROM otp_codes
WHERE identifier = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type GetValidOTPParams struct {
	Identifier string `json:"identifier"`
	Purpose    string `json:"purpose"`
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getValidOTP, arg.Identifier, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.IdentifierType,
		&i.Code,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otp_codes SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}

const reclaimUnverifiedUser = `-- name: ReclaimUnverifiedUser :one
UPDATE users SET password_hash = $2, name = $3, updated_at = NOW()
WHERE id = $1 AND status = 'UNVERIFIED'
RETURNING id, email, whatsapp, password_hash, email_verified, whatsapp_verified, status, last_login_at, last_login_ip, created_at, updated_at, name
`

type ReclaimUnverifiedUserParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
}

func (q *Queries) ReclaimUnverifiedUser(ctx context.Context, arg ReclaimUnverifiedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, reclaimUnverifiedUser, arg.ID, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Whatsapp,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.WhatsappVerified,
		&i.Status,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const resetPasswordByIdentifier = `-- name: ResetPasswordByIdentifier :exec
UPDATE users SET password_hash = $2, updated_at = NOW()
WHERE email = $1 OR whatsapp = $1
`

type ResetPasswordByIdentifierParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) ResetPasswordByIdentifier(ctx context.Context, arg ResetPasswordByIdentifierParams) error {
	_, err := q.db.Exec(ctx, resetPasswordByIdentifier, arg.Email, arg.PasswordHash)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = NOW(), last_login_ip = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserLastLoginParams struct {
	ID          uuid.UUID   `json:"id"`
	LastLoginIp *netip.Addr `json:"last_login_ip"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.LastLoginIp)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified = TRUE, status = 'ACTIVE', updated_at = NOW() WHERE email = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, email pgtype.Text) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, email)
	return err
}

const verifyUserWhatsApp = `-- name: VerifyUserWhatsApp :exec
UPDATE users SET whatsapp_verified = TRUE, status = 'ACTIVE', updated_at = NOW() WHERE whatsapp = $1
`

func (q *Queries) VerifyUserWhatsApp(ctx context.Context, whatsapp pgtype.Text) error {
	_, err := q.db.Exec(ctx, verifyUserWhatsApp, whatsapp)
	return err
}
