// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: billing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, workspace_id, subscription_id, invoice_number, amount, currency, status, description, due_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, subscription_id, invoice_number, amount, currency, status, description, due_date, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	ID             uuid.UUID      `json:"id"`
	WorkspaceID    uuid.UUID      `json:"workspace_id"`
	SubscriptionID uuid.UUID      `json:"subscription_id"`
	InvoiceNumber  string         `json:"invoice_number"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Status         string         `json:"status"`
	Description    pgtype.Text    `json:"description"`
	DueDate        time.Time      `json:"due_date"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ID,
		arg.WorkspaceID,
		arg.SubscriptionID,
		arg.InvoiceNumber,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.Description,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Description,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, invoice_id, workspace_id, xendit_invoice_id, xendit_payment_url, amount, currency, status, expired_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, invoice_id, workspace_id, xendit_invoice_id, xendit_payment_url, amount, currency, status, payment_method, paid_at, expired_at, failure_reason, xendit_callback_data, created_at, updated_at
`

type CreatePaymentParams struct {
	ID               uuid.UUID      `json:"id"`
	InvoiceID        uuid.UUID      `json:"invoice_id"`
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	XenditInvoiceID  pgtype.Text    `json:"xendit_invoice_id"`
	XenditPaymentUrl pgtype.Text    `json:"xendit_payment_url"`
	Amount           pgtype.Numeric `json:"amount"`
	Currency         string         `json:"currency"`
	Status           string         `json:"status"`
	ExpiredAt        *time.Time     `json:"expired_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.InvoiceID,
		arg.WorkspaceID,
		arg.XenditInvoiceID,
		arg.XenditPaymentUrl,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.ExpiredAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.WorkspaceID,
		&i.XenditInvoiceID,
		&i.XenditPaymentUrl,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.FailureReason,
		&i.XenditCallbackData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, workspace_id, subscription_id, invoice_number, amount, currency, status, description, due_date, paid_at, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Description,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, workspace_id, subscription_id, invoice_number, amount, currency, status, description, due_date, paid_at, created_at, updated_at FROM invoices WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Description,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, invoice_id, workspace_id, xendit_invoice_id, xendit_payment_url, amount, currency, status, payment_method, paid_at, expired_at, failure_reason, xendit_callback_data, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.WorkspaceID,
		&i.XenditInvoiceID,
		&i.XenditPaymentUrl,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.FailureReason,
		&i.XenditCallbackData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByXenditID = `-- name: GetPaymentByXenditID :one
SELECT id, invoice_id, workspace_id, xendit_invoice_id, xendit_payment_url, amount, currency, status, payment_method, paid_at, expired_at, failure_reason, xendit_callback_data, created_at, updated_at FROM payments WHERE xendit_invoice_id = $1
`

func (q *Queries) GetPaymentByXenditID(ctx context.Context, xenditInvoiceID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByXenditID, xenditInvoiceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.WorkspaceID,
		&i.XenditInvoiceID,
		&i.XenditPaymentUrl,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.FailureReason,
		&i.XenditCallbackData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingPaymentByInvoice = `-- name: GetPendingPaymentByInvoice :one
SELECT id, invoice_id, workspace_id, xendit_invoice_id, xendit_payment_url, amount, currency, status, payment_method, paid_at, expired_at, failure_reason, xendit_callback_data, created_at, updated_at FROM payments
WHERE invoice_id = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingPaymentByInvoice(ctx context.Context, invoiceID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentByInvoice, invoiceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.WorkspaceID,
		&i.XenditInvoiceID,
		&i.XenditPaymentUrl,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.FailureReason,
		&i.XenditCallbackData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllInvoices = `-- name: ListAllInvoices :many
SELECT i.id, i.workspace_id, i.subscription_id, i.invoice_number, i.amount, i.currency, i.status, i.description, i.due_date, i.paid_at, i.created_at, i.updated_at, e.nama_utama as workspace_name
FROM invoices i
JOIN entities e ON i.workspace_id = e.id
ORDER BY i.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllInvoicesRow struct {
	ID             uuid.UUID      `json:"id"`
	WorkspaceID    uuid.UUID      `json:"workspace_id"`
	SubscriptionID uuid.UUID      `json:"subscription_id"`
	InvoiceNumber  string         `json:"invoice_number"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Status         string         `json:"status"`
	Description    pgtype.Text    `json:"description"`
	DueDate        time.Time      `json:"due_date"`
	PaidAt         *time.Time     `json:"paid_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	WorkspaceName  string         `json:"workspace_name"`
}

func (q *Queries) ListAllInvoices(ctx context.Context, arg ListAllInvoicesParams) ([]ListAllInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listAllInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllInvoicesRow{}
	for rows.Next() {
		var i ListAllInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Description,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByWorkspace = `-- name: ListInvoicesByWorkspace :many
SELECT id, workspace_id, subscription_id, invoice_number, amount, currency, status, description, due_date, paid_at, created_at, updated_at FROM invoices WHERE workspace_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListInvoicesByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListInvoicesByWorkspace(ctx context.Context, arg ListInvoicesByWorkspaceParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Description,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, invoice_id, workspace_id, xendit_invoice_id, xendit_payment_url, amount, currency, status, payment_method, paid_at, expired_at, failure_reason, xendit_callback_data, created_at, updated_at FROM payments WHERE invoice_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, invoiceID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.WorkspaceID,
			&i.XenditInvoiceID,
			&i.XenditPaymentUrl,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.FailureReason,
			&i.XenditCallbackData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByWorkspace = `-- name: ListPaymentsByWorkspace :many
SELECT id, invoice_id, workspace_id, xendit_invoice_id, xendit_payment_url, amount, currency, status, payment_method, paid_at, expired_at, failure_reason, xendit_callback_data, created_at, updated_at FROM payments WHERE workspace_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPaymentsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListPaymentsByWorkspace(ctx context.Context, arg ListPaymentsByWorkspaceParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.WorkspaceID,
			&i.XenditInvoiceID,
			&i.XenditPaymentUrl,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.FailureReason,
			&i.XenditCallbackData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvoices = `-- name: ListPendingInvoices :many
SELECT id, workspace_id, subscription_id, invoice_number, amount, currency, status, description, due_date, paid_at, created_at, updated_at FROM invoices WHERE status = 'pending' AND due_date < NOW() ORDER BY due_date ASC
`

func (q *Queries) ListPendingInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listPendingInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Description,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :exec
UPDATE invoices SET status = 'paid', paid_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkInvoicePaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvoicePaid, id)
	return err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoices SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateInvoiceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	return err
}

const updatePaymentExpired = `-- name: UpdatePaymentExpired :exec
UPDATE payments SET status = 'expired', updated_at = NOW()
WHERE status = 'pending' AND expired_at < NOW()
`

func (q *Queries) UpdatePaymentExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updatePaymentExpired)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = $2, payment_method = $3, paid_at = $4, failure_reason = $5, xendit_callback_data = $6, updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID                 uuid.UUID   `json:"id"`
	Status             string      `json:"status"`
	PaymentMethod      pgtype.Text `json:"payment_method"`
	PaidAt             *time.Time  `json:"paid_at"`
	FailureReason      pgtype.Text `json:"failure_reason"`
	XenditCallbackData []byte      `json:"xendit_callback_data"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.PaymentMethod,
		arg.PaidAt,
		arg.FailureReason,
		arg.XenditCallbackData,
	)
	return err
}
