// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: company_identity.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveCompanyClaim = `-- name: ApproveCompanyClaim :exec
UPDATE company_claims
SET status = 'APPROVED', reviewer_id = $2, reviewed_at = $3, notes = $4, updated_at = NOW()
WHERE id = $1
`

type ApproveCompanyClaimParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewerID pgtype.UUID `json:"reviewer_id"`
	ReviewedAt *time.Time  `json:"reviewed_at"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) ApproveCompanyClaim(ctx context.Context, arg ApproveCompanyClaimParams) error {
	_, err := q.db.Exec(ctx, approveCompanyClaim,
		arg.ID,
		arg.ReviewerID,
		arg.ReviewedAt,
		arg.Notes,
	)
	return err
}

const assignClaimReviewer = `-- name: AssignClaimReviewer :exec
UPDATE company_claims
SET reviewer_id = $2, status = 'UNDER_REVIEW', updated_at = NOW()
WHERE id = $1
`

type AssignClaimReviewerParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewerID pgtype.UUID `json:"reviewer_id"`
}

func (q *Queries) AssignClaimReviewer(ctx context.Context, arg AssignClaimReviewerParams) error {
	_, err := q.db.Exec(ctx, assignClaimReviewer, arg.ID, arg.ReviewerID)
	return err
}

const countClaimDocuments = `-- name: CountClaimDocuments :one
SELECT COUNT(*) FROM claim_documents WHERE claim_id = $1 AND upload_status = 'UPLOADED'
`

func (q *Queries) CountClaimDocuments(ctx context.Context, claimID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimDocuments, claimID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClaimsByStatus = `-- name: CountClaimsByStatus :one
SELECT COUNT(*) FROM company_claims WHERE status = $1
`

func (q *Queries) CountClaimsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClaimAuditEntry = `-- name: CreateClaimAuditEntry :exec

INSERT INTO claim_audit_log (id, claim_id, actor_id, actor_type, action, old_status, new_status, details, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateClaimAuditEntryParams struct {
	ID        uuid.UUID   `json:"id"`
	ClaimID   uuid.UUID   `json:"claim_id"`
	ActorID   uuid.UUID   `json:"actor_id"`
	ActorType string      `json:"actor_type"`
	Action    string      `json:"action"`
	OldStatus pgtype.Text `json:"old_status"`
	NewStatus pgtype.Text `json:"new_status"`
	Details   []byte      `json:"details"`
	CreatedAt time.Time   `json:"created_at"`
}

// ============================================================
// Claim Audit Log
// ============================================================
func (q *Queries) CreateClaimAuditEntry(ctx context.Context, arg CreateClaimAuditEntryParams) error {
	_, err := q.db.Exec(ctx, createClaimAuditEntry,
		arg.ID,
		arg.ClaimID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.OldStatus,
		arg.NewStatus,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const createClaimDocument = `-- name: CreateClaimDocument :one

INSERT INTO claim_documents (id, claim_id, document_type, file_key, file_name, file_size, mime_type, upload_status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, claim_id, document_type, file_key, file_name, file_size, mime_type, upload_status, uploaded_at, created_at
`

type CreateClaimDocumentParams struct {
	ID           uuid.UUID `json:"id"`
	ClaimID      uuid.UUID `json:"claim_id"`
	DocumentType string    `json:"document_type"`
	FileKey      string    `json:"file_key"`
	FileName     string    `json:"file_name"`
	FileSize     int64     `json:"file_size"`
	MimeType     string    `json:"mime_type"`
	UploadStatus string    `json:"upload_status"`
	CreatedAt    time.Time `json:"created_at"`
}

// ============================================================
// Claim Documents
// ============================================================
func (q *Queries) CreateClaimDocument(ctx context.Context, arg CreateClaimDocumentParams) (ClaimDocument, error) {
	row := q.db.QueryRow(ctx, createClaimDocument,
		arg.ID,
		arg.ClaimID,
		arg.DocumentType,
		arg.FileKey,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.UploadStatus,
		arg.CreatedAt,
	)
	var i ClaimDocument
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.DocumentType,
		&i.FileKey,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.UploadStatus,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompanyClaim = `-- name: CreateCompanyClaim :one

INSERT INTO company_claims (id, entity_id, claimant_user_id, claimant_entity_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, entity_id, claimant_user_id, claimant_entity_id, status, reviewer_id, reviewed_at, rejection_reason, dispute_reason, notes, created_at, updated_at
`

type CreateCompanyClaimParams struct {
	ID               uuid.UUID `json:"id"`
	EntityID         uuid.UUID `json:"entity_id"`
	ClaimantUserID   uuid.UUID `json:"claimant_user_id"`
	ClaimantEntityID uuid.UUID `json:"claimant_entity_id"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// ============================================================
// Company Claims
// ============================================================
func (q *Queries) CreateCompanyClaim(ctx context.Context, arg CreateCompanyClaimParams) (CompanyClaim, error) {
	row := q.db.QueryRow(ctx, createCompanyClaim,
		arg.ID,
		arg.EntityID,
		arg.ClaimantUserID,
		arg.ClaimantEntityID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CompanyClaim
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ClaimantUserID,
		&i.ClaimantEntityID,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.DisputeReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCounterpartyAlias = `-- name: CreateCounterpartyAlias :one

INSERT INTO counterparty_aliases (id, workspace_id, entity_id, custom_alias, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, entity_id, custom_alias, created_at, updated_at
`

type CreateCounterpartyAliasParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	EntityID    uuid.UUID `json:"entity_id"`
	CustomAlias string    `json:"custom_alias"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ============================================================
// Counterparty Aliases
// ============================================================
func (q *Queries) CreateCounterpartyAlias(ctx context.Context, arg CreateCounterpartyAliasParams) (CounterpartyAlias, error) {
	row := q.db.QueryRow(ctx, createCounterpartyAlias,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityID,
		arg.CustomAlias,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CounterpartyAlias
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityID,
		&i.CustomAlias,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEntityAlias = `-- name: CreateEntityAlias :one

INSERT INTO entity_aliases (id, entity_id, alias, alias_normalized, source, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entity_id, alias, alias_normalized, source, created_at
`

type CreateEntityAliasParams struct {
	ID              uuid.UUID `json:"id"`
	EntityID        uuid.UUID `json:"entity_id"`
	Alias           string    `json:"alias"`
	AliasNormalized string    `json:"alias_normalized"`
	Source          string    `json:"source"`
	CreatedAt       time.Time `json:"created_at"`
}

// ============================================================
// Entity Aliases
// ============================================================
func (q *Queries) CreateEntityAlias(ctx context.Context, arg CreateEntityAliasParams) (EntityAlias, error) {
	row := q.db.QueryRow(ctx, createEntityAlias,
		arg.ID,
		arg.EntityID,
		arg.Alias,
		arg.AliasNormalized,
		arg.Source,
		arg.CreatedAt,
	)
	var i EntityAlias
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.Alias,
		&i.AliasNormalized,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createEntityLegalID = `-- name: CreateEntityLegalID :one

INSERT INTO entity_legal_ids (id, entity_id, id_type, id_value, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entity_id, id_type, id_value, is_verified, verified_at, created_at, updated_at
`

type CreateEntityLegalIDParams struct {
	ID        uuid.UUID `json:"id"`
	EntityID  uuid.UUID `json:"entity_id"`
	IDType    string    `json:"id_type"`
	IDValue   string    `json:"id_value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ============================================================
// Entity Legal IDs
// ============================================================
func (q *Queries) CreateEntityLegalID(ctx context.Context, arg CreateEntityLegalIDParams) (EntityLegalID, error) {
	row := q.db.QueryRow(ctx, createEntityLegalID,
		arg.ID,
		arg.EntityID,
		arg.IDType,
		arg.IDValue,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityLegalID
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.IDType,
		&i.IDValue,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEntityVerification = `-- name: CreateEntityVerification :one

INSERT INTO entity_verification (id, entity_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, entity_id, status, verified_by, verified_at, rejection_reason, notes, created_at, updated_at
`

type CreateEntityVerificationParams struct {
	ID        uuid.UUID `json:"id"`
	EntityID  uuid.UUID `json:"entity_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ============================================================
// Entity Verification
// ============================================================
func (q *Queries) CreateEntityVerification(ctx context.Context, arg CreateEntityVerificationParams) (EntityVerification, error) {
	row := q.db.QueryRow(ctx, createEntityVerification,
		arg.ID,
		arg.EntityID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityVerification
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCounterpartyAlias = `-- name: DeleteCounterpartyAlias :exec
DELETE FROM counterparty_aliases WHERE workspace_id = $1 AND entity_id = $2
`

type DeleteCounterpartyAliasParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	EntityID    uuid.UUID `json:"entity_id"`
}

func (q *Queries) DeleteCounterpartyAlias(ctx context.Context, arg DeleteCounterpartyAliasParams) error {
	_, err := q.db.Exec(ctx, deleteCounterpartyAlias, arg.WorkspaceID, arg.EntityID)
	return err
}

const deleteEntityAlias = `-- name: DeleteEntityAlias :exec
DELETE FROM entity_aliases WHERE id = $1 AND entity_id = $2
`

type DeleteEntityAliasParams struct {
	ID       uuid.UUID `json:"id"`
	EntityID uuid.UUID `json:"entity_id"`
}

func (q *Queries) DeleteEntityAlias(ctx context.Context, arg DeleteEntityAliasParams) error {
	_, err := q.db.Exec(ctx, deleteEntityAlias, arg.ID, arg.EntityID)
	return err
}

const deleteEntityLegalID = `-- name: DeleteEntityLegalID :exec
DELETE FROM entity_legal_ids WHERE entity_id = $1 AND id_type = $2
`

type DeleteEntityLegalIDParams struct {
	EntityID uuid.UUID `json:"entity_id"`
	IDType   string    `json:"id_type"`
}

func (q *Queries) DeleteEntityLegalID(ctx context.Context, arg DeleteEntityLegalIDParams) error {
	_, err := q.db.Exec(ctx, deleteEntityLegalID, arg.EntityID, arg.IDType)
	return err
}

const disputeCompanyClaim = `-- name: DisputeCompanyClaim :exec
UPDATE company_claims
SET status = 'DISPUTED', dispute_reason = $2, updated_at = NOW()
WHERE id = $1
`

type DisputeCompanyClaimParams struct {
	ID            uuid.UUID   `json:"id"`
	DisputeReason pgtype.Text `json:"dispute_reason"`
}

func (q *Queries) DisputeCompanyClaim(ctx context.Context, arg DisputeCompanyClaimParams) error {
	_, err := q.db.Exec(ctx, disputeCompanyClaim, arg.ID, arg.DisputeReason)
	return err
}

const findDuplicateEntities = `-- name: FindDuplicateEntities :many
SELECT id, user_id, entity_type, nama_utama, nik_npwp, nomor_wa, alamat_lengkap, is_shadow, status, created_at, updated_at, nama_normalized, similarity(nama_normalized, $1) as match_score
FROM entities
WHERE nama_normalized % $1
  AND id != $2
  AND status = 'ACTIVE'
  AND similarity(nama_normalized, $1) >= 0.4
ORDER BY similarity(nama_normalized, $1) DESC
LIMIT $3
`

type FindDuplicateEntitiesParams struct {
	Similarity string    `json:"similarity"`
	ID         uuid.UUID `json:"id"`
	Limit      int32     `json:"limit"`
}

type FindDuplicateEntitiesRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	EntityType     string      `json:"entity_type"`
	NamaUtama      string      `json:"nama_utama"`
	NikNpwp        pgtype.Text `json:"nik_npwp"`
	NomorWa        pgtype.Text `json:"nomor_wa"`
	AlamatLengkap  pgtype.Text `json:"alamat_lengkap"`
	IsShadow       bool        `json:"is_shadow"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	NamaNormalized pgtype.Text `json:"nama_normalized"`
	MatchScore     float32     `json:"match_score"`
}

func (q *Queries) FindDuplicateEntities(ctx context.Context, arg FindDuplicateEntitiesParams) ([]FindDuplicateEntitiesRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateEntities, arg.Similarity, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDuplicateEntitiesRow{}
	for rows.Next() {
		var i FindDuplicateEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.NamaUtama,
			&i.NikNpwp,
			&i.NomorWa,
			&i.AlamatLengkap,
			&i.IsShadow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaNormalized,
			&i.MatchScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveClaimForEntity = `-- name: GetActiveClaimForEntity :one
SELECT id, entity_id, claimant_user_id, claimant_entity_id, status, reviewer_id, reviewed_at, rejection_reason, dispute_reason, notes, created_at, updated_at FROM company_claims
WHERE entity_id = $1 AND status NOT IN ('REJECTED', 'APPROVED')
LIMIT 1
`

func (q *Queries) GetActiveClaimForEntity(ctx context.Context, entityID uuid.UUID) (CompanyClaim, error) {
	row := q.db.QueryRow(ctx, getActiveClaimForEntity, entityID)
	var i CompanyClaim
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ClaimantUserID,
		&i.ClaimantEntityID,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.DisputeReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimAuditLog = `-- name: GetClaimAuditLog :many
SELECT id, claim_id, actor_id, actor_type, action, old_status, new_status, details, created_at FROM claim_audit_log WHERE claim_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetClaimAuditLog(ctx context.Context, claimID uuid.UUID) ([]ClaimAuditLog, error) {
	rows, err := q.db.Query(ctx, getClaimAuditLog, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimAuditLog{}
	for rows.Next() {
		var i ClaimAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.OldStatus,
			&i.NewStatus,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimDocumentByID = `-- name: GetClaimDocumentByID :one
SELECT id, claim_id, document_type, file_key, file_name, file_size, mime_type, upload_status, uploaded_at, created_at FROM claim_documents WHERE id = $1
`

func (q *Queries) GetClaimDocumentByID(ctx context.Context, id uuid.UUID) (ClaimDocument, error) {
	row := q.db.QueryRow(ctx, getClaimDocumentByID, id)
	var i ClaimDocument
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.DocumentType,
		&i.FileKey,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.UploadStatus,
		&i.UploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getClaimDocuments = `-- name: GetClaimDocuments :many
SELECT id, claim_id, document_type, file_key, file_name, file_size, mime_type, upload_status, uploaded_at, created_at FROM claim_documents WHERE claim_id = $1 ORDER BY created_at
`

func (q *Queries) GetClaimDocuments(ctx context.Context, claimID uuid.UUID) ([]ClaimDocument, error) {
	rows, err := q.db.Query(ctx, getClaimDocuments, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDocument{}
	for rows.Next() {
		var i ClaimDocument
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.DocumentType,
			&i.FileKey,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.UploadStatus,
			&i.UploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimsByClaimant = `-- name: GetClaimsByClaimant :many
SELECT cc.id, cc.entity_id, cc.claimant_user_id, cc.claimant_entity_id, cc.status, cc.reviewer_id, cc.reviewed_at, cc.rejection_reason, cc.dispute_reason, cc.notes, cc.created_at, cc.updated_at, e.nama_utama as entity_name, e.entity_type
FROM company_claims cc
JOIN entities e ON e.id = cc.entity_id
WHERE cc.claimant_user_id = $1
ORDER BY cc.created_at DESC
`

type GetClaimsByClaimantRow struct {
	ID               uuid.UUID   `json:"id"`
	EntityID         uuid.UUID   `json:"entity_id"`
	ClaimantUserID   uuid.UUID   `json:"claimant_user_id"`
	ClaimantEntityID uuid.UUID   `json:"claimant_entity_id"`
	Status           string      `json:"status"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
	ReviewedAt       *time.Time  `json:"reviewed_at"`
	RejectionReason  pgtype.Text `json:"rejection_reason"`
	DisputeReason    pgtype.Text `json:"dispute_reason"`
	Notes            pgtype.Text `json:"notes"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	EntityName       string      `json:"entity_name"`
	EntityType       string      `json:"entity_type"`
}

func (q *Queries) GetClaimsByClaimant(ctx context.Context, claimantUserID uuid.UUID) ([]GetClaimsByClaimantRow, error) {
	rows, err := q.db.Query(ctx, getClaimsByClaimant, claimantUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClaimsByClaimantRow{}
	for rows.Next() {
		var i GetClaimsByClaimantRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.ClaimantUserID,
			&i.ClaimantEntityID,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.DisputeReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntityName,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompanyClaimByID = `-- name: GetCompanyClaimByID :one
SELECT id, entity_id, claimant_user_id, claimant_entity_id, status, reviewer_id, reviewed_at, rejection_reason, dispute_reason, notes, created_at, updated_at FROM company_claims WHERE id = $1
`

func (q *Queries) GetCompanyClaimByID(ctx context.Context, id uuid.UUID) (CompanyClaim, error) {
	row := q.db.QueryRow(ctx, getCompanyClaimByID, id)
	var i CompanyClaim
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ClaimantUserID,
		&i.ClaimantEntityID,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.DisputeReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCounterpartyAlias = `-- name: GetCounterpartyAlias :one
SELECT id, workspace_id, entity_id, custom_alias, created_at, updated_at FROM counterparty_aliases WHERE workspace_id = $1 AND entity_id = $2
`

type GetCounterpartyAliasParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	EntityID    uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetCounterpartyAlias(ctx context.Context, arg GetCounterpartyAliasParams) (CounterpartyAlias, error) {
	row := q.db.QueryRow(ctx, getCounterpartyAlias, arg.WorkspaceID, arg.EntityID)
	var i CounterpartyAlias
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityID,
		&i.CustomAlias,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityAliases = `-- name: GetEntityAliases :many
SELECT id, entity_id, alias, alias_normalized, source, created_at FROM entity_aliases WHERE entity_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEntityAliases(ctx context.Context, entityID uuid.UUID) ([]EntityAlias, error) {
	rows, err := q.db.Query(ctx, getEntityAliases, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAlias{}
	for rows.Next() {
		var i EntityAlias
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.Alias,
			&i.AliasNormalized,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityByLegalID = `-- name: GetEntityByLegalID :one
SELECT e.id, e.user_id, e.entity_type, e.nama_utama, e.nik_npwp, e.nomor_wa, e.alamat_lengkap, e.is_shadow, e.status, e.created_at, e.updated_at, e.nama_normalized FROM entities e
JOIN entity_legal_ids eli ON eli.entity_id = e.id
WHERE eli.id_type = $1 AND eli.id_value = $2
`

type GetEntityByLegalIDParams struct {
	IDType  string `json:"id_type"`
	IDValue string `json:"id_value"`
}

func (q *Queries) GetEntityByLegalID(ctx context.Context, arg GetEntityByLegalIDParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByLegalID, arg.IDType, arg.IDValue)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.NamaUtama,
		&i.NikNpwp,
		&i.NomorWa,
		&i.AlamatLengkap,
		&i.IsShadow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamaNormalized,
	)
	return i, err
}

const getEntityLegalIDs = `-- name: GetEntityLegalIDs :many
SELECT id, entity_id, id_type, id_value, is_verified, verified_at, created_at, updated_at FROM entity_legal_ids WHERE entity_id = $1 ORDER BY id_type
`

func (q *Queries) GetEntityLegalIDs(ctx context.Context, entityID uuid.UUID) ([]EntityLegalID, error) {
	rows, err := q.db.Query(ctx, getEntityLegalIDs, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityLegalID{}
	for rows.Next() {
		var i EntityLegalID
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.IDType,
			&i.IDValue,
			&i.IsVerified,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityVerification = `-- name: GetEntityVerification :one
SELECT id, entity_id, status, verified_by, verified_at, rejection_reason, notes, created_at, updated_at FROM entity_verification WHERE entity_id = $1
`

func (q *Queries) GetEntityVerification(ctx context.Context, entityID uuid.UUID) (EntityVerification, error) {
	row := q.db.QueryRow(ctx, getEntityVerification, entityID)
	var i EntityVerification
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasClaimForEntity = `-- name: HasClaimForEntity :one
SELECT EXISTS(SELECT 1 FROM company_claims WHERE entity_id = $1)
`

func (q *Queries) HasClaimForEntity(ctx context.Context, entityID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasClaimForEntity, entityID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkShadowEntity = `-- name: LinkShadowEntity :exec
UPDATE entities
SET user_id = $2, is_shadow = FALSE, status = 'CLAIMED', updated_at = NOW()
WHERE id = $1 AND is_shadow = TRUE
`

type LinkShadowEntityParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) LinkShadowEntity(ctx context.Context, arg LinkShadowEntityParams) error {
	_, err := q.db.Exec(ctx, linkShadowEntity, arg.ID, arg.UserID)
	return err
}

const listAllClaims = `-- name: ListAllClaims :many
SELECT cc.id, cc.entity_id, cc.claimant_user_id, cc.claimant_entity_id, cc.status, cc.reviewer_id, cc.reviewed_at, cc.rejection_reason, cc.dispute_reason, cc.notes, cc.created_at, cc.updated_at, e.nama_utama as entity_name, e.entity_type, u.name as claimant_name
FROM company_claims cc
JOIN entities e ON e.id = cc.entity_id
JOIN users u ON u.id = cc.claimant_user_id
ORDER BY cc.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllClaimsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllClaimsRow struct {
	ID               uuid.UUID   `json:"id"`
	EntityID         uuid.UUID   `json:"entity_id"`
	ClaimantUserID   uuid.UUID   `json:"claimant_user_id"`
	ClaimantEntityID uuid.UUID   `json:"claimant_entity_id"`
	Status           string      `json:"status"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
	ReviewedAt       *time.Time  `json:"reviewed_at"`
	RejectionReason  pgtype.Text `json:"rejection_reason"`
	DisputeReason    pgtype.Text `json:"dispute_reason"`
	Notes            pgtype.Text `json:"notes"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	EntityName       string      `json:"entity_name"`
	EntityType       string      `json:"entity_type"`
	ClaimantName     pgtype.Text `json:"claimant_name"`
}

func (q *Queries) ListAllClaims(ctx context.Context, arg ListAllClaimsParams) ([]ListAllClaimsRow, error) {
	rows, err := q.db.Query(ctx, listAllClaims, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllClaimsRow{}
	for rows.Next() {
		var i ListAllClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.ClaimantUserID,
			&i.ClaimantEntityID,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.DisputeReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntityName,
			&i.EntityType,
			&i.ClaimantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsByStatus = `-- name: ListClaimsByStatus :many
SELECT cc.id, cc.entity_id, cc.claimant_user_id, cc.claimant_entity_id, cc.status, cc.reviewer_id, cc.reviewed_at, cc.rejection_reason, cc.dispute_reason, cc.notes, cc.created_at, cc.updated_at, e.nama_utama as entity_name, e.entity_type, u.name as claimant_name
FROM company_claims cc
JOIN entities e ON e.id = cc.entity_id
JOIN users u ON u.id = cc.claimant_user_id
WHERE cc.status = $1
ORDER BY cc.created_at ASC
LIMIT $2 OFFSET $3
`

type ListClaimsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListClaimsByStatusRow struct {
	ID               uuid.UUID   `json:"id"`
	EntityID         uuid.UUID   `json:"entity_id"`
	ClaimantUserID   uuid.UUID   `json:"claimant_user_id"`
	ClaimantEntityID uuid.UUID   `json:"claimant_entity_id"`
	Status           string      `json:"status"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
	ReviewedAt       *time.Time  `json:"reviewed_at"`
	RejectionReason  pgtype.Text `json:"rejection_reason"`
	DisputeReason    pgtype.Text `json:"dispute_reason"`
	Notes            pgtype.Text `json:"notes"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	EntityName       string      `json:"entity_name"`
	EntityType       string      `json:"entity_type"`
	ClaimantName     pgtype.Text `json:"claimant_name"`
}

func (q *Queries) ListClaimsByStatus(ctx context.Context, arg ListClaimsByStatusParams) ([]ListClaimsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listClaimsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimsByStatusRow{}
	for rows.Next() {
		var i ListClaimsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.ClaimantUserID,
			&i.ClaimantEntityID,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.DisputeReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntityName,
			&i.EntityType,
			&i.ClaimantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterpartyAliases = `-- name: ListCounterpartyAliases :many
SELECT ca.id, ca.workspace_id, ca.entity_id, ca.custom_alias, ca.created_at, ca.updated_at, e.nama_utama as entity_name
FROM counterparty_aliases ca
JOIN entities e ON e.id = ca.entity_id
WHERE ca.workspace_id = $1
ORDER BY ca.custom_alias ASC
`

type ListCounterpartyAliasesRow struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	EntityID    uuid.UUID `json:"entity_id"`
	CustomAlias string    `json:"custom_alias"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	EntityName  string    `json:"entity_name"`
}

func (q *Queries) ListCounterpartyAliases(ctx context.Context, workspaceID uuid.UUID) ([]ListCounterpartyAliasesRow, error) {
	rows, err := q.db.Query(ctx, listCounterpartyAliases, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterpartyAliasesRow{}
	for rows.Next() {
		var i ListCounterpartyAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityID,
			&i.CustomAlias,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByVerificationStatus = `-- name: ListEntitiesByVerificationStatus :many
SELECT ev.id, ev.entity_id, ev.status, ev.verified_by, ev.verified_at, ev.rejection_reason, ev.notes, ev.created_at, ev.updated_at, e.nama_utama, e.entity_type, e.is_shadow
FROM entity_verification ev
JOIN entities e ON e.id = ev.entity_id
WHERE ev.status = $1
ORDER BY ev.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListEntitiesByVerificationStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListEntitiesByVerificationStatusRow struct {
	ID              uuid.UUID   `json:"id"`
	EntityID        uuid.UUID   `json:"entity_id"`
	Status          string      `json:"status"`
	VerifiedBy      pgtype.UUID `json:"verified_by"`
	VerifiedAt      *time.Time  `json:"verified_at"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	Notes           pgtype.Text `json:"notes"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	NamaUtama       string      `json:"nama_utama"`
	EntityType      string      `json:"entity_type"`
	IsShadow        bool        `json:"is_shadow"`
}

func (q *Queries) ListEntitiesByVerificationStatus(ctx context.Context, arg ListEntitiesByVerificationStatusParams) ([]ListEntitiesByVerificationStatusRow, error) {
	rows, err := q.db.Query(ctx, listEntitiesByVerificationStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitiesByVerificationStatusRow{}
	for rows.Next() {
		var i ListEntitiesByVerificationStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.Status,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaUtama,
			&i.EntityType,
			&i.IsShadow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentUploaded = `-- name: MarkDocumentUploaded :exec
UPDATE claim_documents SET upload_status = 'UPLOADED', uploaded_at = NOW() WHERE id = $1
`

func (q *Queries) MarkDocumentUploaded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDocumentUploaded, id)
	return err
}

const rejectCompanyClaim = `-- name: RejectCompanyClaim :exec
UPDATE company_claims
SET status = 'REJECTED', reviewer_id = $2, reviewed_at = $3, rejection_reason = $4, updated_at = NOW()
WHERE id = $1
`

type RejectCompanyClaimParams struct {
	ID              uuid.UUID   `json:"id"`
	ReviewerID      pgtype.UUID `json:"reviewer_id"`
	ReviewedAt      *time.Time  `json:"reviewed_at"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) RejectCompanyClaim(ctx context.Context, arg RejectCompanyClaimParams) error {
	_, err := q.db.Exec(ctx, rejectCompanyClaim,
		arg.ID,
		arg.ReviewerID,
		arg.ReviewedAt,
		arg.RejectionReason,
	)
	return err
}

const resubmitCompanyClaim = `-- name: ResubmitCompanyClaim :exec
UPDATE company_claims
SET status = 'SUBMITTED',
    rejection_reason = NULL,
    dispute_reason = NULL,
    reviewer_id = NULL,
    reviewed_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResubmitCompanyClaim(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resubmitCompanyClaim, id)
	return err
}

const searchCounterpartiesFuzzy = `-- name: SearchCounterpartiesFuzzy :many

SELECT e.id, e.nama_utama, e.entity_type, e.is_shadow,
       similarity(e.nama_normalized, $1) as match_score
FROM entities e
WHERE e.nama_normalized % $1
  AND e.status = 'ACTIVE'
  AND e.entity_type = 'BADAN_USAHA'
  AND (
    e.is_shadow = TRUE
    OR EXISTS (
      SELECT 1 FROM entity_relations er
      WHERE er.subject_id = e.id
        AND er.object_id = $3
        AND er.relation_type IN ('PELANGGAN', 'VENDOR')
    )
  )
ORDER BY similarity(e.nama_normalized, $1) DESC
LIMIT $2
`

type SearchCounterpartiesFuzzyParams struct {
	Similarity string    `json:"similarity"`
	Limit      int32     `json:"limit"`
	ObjectID   uuid.UUID `json:"object_id"`
}

type SearchCounterpartiesFuzzyRow struct {
	ID         uuid.UUID `json:"id"`
	NamaUtama  string    `json:"nama_utama"`
	EntityType string    `json:"entity_type"`
	IsShadow   bool      `json:"is_shadow"`
	MatchScore float32   `json:"match_score"`
}

// ============================================================
// Counterparty Search (privacy-safe)
// ============================================================
func (q *Queries) SearchCounterpartiesFuzzy(ctx context.Context, arg SearchCounterpartiesFuzzyParams) ([]SearchCounterpartiesFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchCounterpartiesFuzzy, arg.Similarity, arg.Limit, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCounterpartiesFuzzyRow{}
	for rows.Next() {
		var i SearchCounterpartiesFuzzyRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaUtama,
			&i.EntityType,
			&i.IsShadow,
			&i.MatchScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEntitiesByAlias = `-- name: SearchEntitiesByAlias :many
SELECT DISTINCT ON (e.id) e.id, e.user_id, e.entity_type, e.nama_utama, e.nik_npwp, e.nomor_wa, e.alamat_lengkap, e.is_shadow, e.status, e.created_at, e.updated_at, e.nama_normalized, similarity(ea.alias_normalized, $1) as match_score
FROM entities e
JOIN entity_aliases ea ON ea.entity_id = e.id
WHERE ea.alias_normalized % $1
ORDER BY e.id, similarity(ea.alias_normalized, $1) DESC
LIMIT $2
`

type SearchEntitiesByAliasParams struct {
	Similarity string `json:"similarity"`
	Limit      int32  `json:"limit"`
}

type SearchEntitiesByAliasRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	EntityType     string      `json:"entity_type"`
	NamaUtama      string      `json:"nama_utama"`
	NikNpwp        pgtype.Text `json:"nik_npwp"`
	NomorWa        pgtype.Text `json:"nomor_wa"`
	AlamatLengkap  pgtype.Text `json:"alamat_lengkap"`
	IsShadow       bool        `json:"is_shadow"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	NamaNormalized pgtype.Text `json:"nama_normalized"`
	MatchScore     float32     `json:"match_score"`
}

func (q *Queries) SearchEntitiesByAlias(ctx context.Context, arg SearchEntitiesByAliasParams) ([]SearchEntitiesByAliasRow, error) {
	rows, err := q.db.Query(ctx, searchEntitiesByAlias, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEntitiesByAliasRow{}
	for rows.Next() {
		var i SearchEntitiesByAliasRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.NamaUtama,
			&i.NikNpwp,
			&i.NomorWa,
			&i.AlamatLengkap,
			&i.IsShadow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaNormalized,
			&i.MatchScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEntitiesFuzzy = `-- name: SearchEntitiesFuzzy :many
SELECT e.id, e.user_id, e.entity_type, e.nama_utama, e.nik_npwp, e.nomor_wa, e.alamat_lengkap, e.is_shadow, e.status, e.created_at, e.updated_at, e.nama_normalized, similarity(e.nama_normalized, $2) as match_score
FROM entities e
INNER JOIN entity_relations er ON er.subject_id = e.id
WHERE er.object_id = $1
  AND er.relation_type IN ('PELANGGAN', 'VENDOR')
  AND er.status = 'ACTIVE'
  AND e.nama_normalized % $2
  AND e.status = 'ACTIVE'
ORDER BY similarity(e.nama_normalized, $2) DESC
LIMIT $3 OFFSET $4
`

type SearchEntitiesFuzzyParams struct {
	ObjectID   uuid.UUID `json:"object_id"`
	Similarity string    `json:"similarity"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type SearchEntitiesFuzzyRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	EntityType     string      `json:"entity_type"`
	NamaUtama      string      `json:"nama_utama"`
	NikNpwp        pgtype.Text `json:"nik_npwp"`
	NomorWa        pgtype.Text `json:"nomor_wa"`
	AlamatLengkap  pgtype.Text `json:"alamat_lengkap"`
	IsShadow       bool        `json:"is_shadow"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	NamaNormalized pgtype.Text `json:"nama_normalized"`
	MatchScore     float32     `json:"match_score"`
}

func (q *Queries) SearchEntitiesFuzzy(ctx context.Context, arg SearchEntitiesFuzzyParams) ([]SearchEntitiesFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchEntitiesFuzzy,
		arg.ObjectID,
		arg.Similarity,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEntitiesFuzzyRow{}
	for rows.Next() {
		var i SearchEntitiesFuzzyRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.NamaUtama,
			&i.NikNpwp,
			&i.NomorWa,
			&i.AlamatLengkap,
			&i.IsShadow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaNormalized,
			&i.MatchScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClaimStatus = `-- name: UpdateClaimStatus :exec
UPDATE company_claims
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateClaimStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateClaimStatus(ctx context.Context, arg UpdateClaimStatusParams) error {
	_, err := q.db.Exec(ctx, updateClaimStatus, arg.ID, arg.Status)
	return err
}

const updateCounterpartyAlias = `-- name: UpdateCounterpartyAlias :exec
UPDATE counterparty_aliases
SET custom_alias = $3, updated_at = NOW()
WHERE workspace_id = $1 AND entity_id = $2
`

type UpdateCounterpartyAliasParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	EntityID    uuid.UUID `json:"entity_id"`
	CustomAlias string    `json:"custom_alias"`
}

func (q *Queries) UpdateCounterpartyAlias(ctx context.Context, arg UpdateCounterpartyAliasParams) error {
	_, err := q.db.Exec(ctx, updateCounterpartyAlias, arg.WorkspaceID, arg.EntityID, arg.CustomAlias)
	return err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE claim_documents SET upload_status = $2 WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID           uuid.UUID `json:"id"`
	UploadStatus string    `json:"upload_status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.ID, arg.UploadStatus)
	return err
}

const updateEntityLegalID = `-- name: UpdateEntityLegalID :exec
UPDATE entity_legal_ids
SET id_value = $3, updated_at = NOW()
WHERE entity_id = $1 AND id_type = $2
`

type UpdateEntityLegalIDParams struct {
	EntityID uuid.UUID `json:"entity_id"`
	IDType   string    `json:"id_type"`
	IDValue  string    `json:"id_value"`
}

func (q *Queries) UpdateEntityLegalID(ctx context.Context, arg UpdateEntityLegalIDParams) error {
	_, err := q.db.Exec(ctx, updateEntityLegalID, arg.EntityID, arg.IDType, arg.IDValue)
	return err
}

const updateEntityNormalizedName = `-- name: UpdateEntityNormalizedName :exec

UPDATE entities SET nama_normalized = $2, updated_at = NOW() WHERE id = $1
`

type UpdateEntityNormalizedNameParams struct {
	ID             uuid.UUID   `json:"id"`
	NamaNormalized pgtype.Text `json:"nama_normalized"`
}

// ============================================================
// Normalized Name & Fuzzy Search
// ============================================================
func (q *Queries) UpdateEntityNormalizedName(ctx context.Context, arg UpdateEntityNormalizedNameParams) error {
	_, err := q.db.Exec(ctx, updateEntityNormalizedName, arg.ID, arg.NamaNormalized)
	return err
}

const updateEntityVerificationStatus = `-- name: UpdateEntityVerificationStatus :exec
UPDATE entity_verification
SET status = $2, verified_by = $3, verified_at = $4, rejection_reason = $5, notes = $6, updated_at = NOW()
WHERE entity_id = $1
`

type UpdateEntityVerificationStatusParams struct {
	EntityID        uuid.UUID   `json:"entity_id"`
	Status          string      `json:"status"`
	VerifiedBy      pgtype.UUID `json:"verified_by"`
	VerifiedAt      *time.Time  `json:"verified_at"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateEntityVerificationStatus(ctx context.Context, arg UpdateEntityVerificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateEntityVerificationStatus,
		arg.EntityID,
		arg.Status,
		arg.VerifiedBy,
		arg.VerifiedAt,
		arg.RejectionReason,
		arg.Notes,
	)
	return err
}

const userCanManageClaimEntity = `-- name: UserCanManageClaimEntity :one
SELECT EXISTS(
    SELECT 1 FROM company_claims
    WHERE entity_id = $1 AND claimant_user_id = $2
      AND status IN ('DRAFT', 'REJECTED', 'DISPUTED')
)
`

type UserCanManageClaimEntityParams struct {
	EntityID       uuid.UUID `json:"entity_id"`
	ClaimantUserID uuid.UUID `json:"claimant_user_id"`
}

func (q *Queries) UserCanManageClaimEntity(ctx context.Context, arg UserCanManageClaimEntityParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanManageClaimEntity, arg.EntityID, arg.ClaimantUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userIsClaimantForEntity = `-- name: UserIsClaimantForEntity :one
SELECT EXISTS(
    SELECT 1 FROM company_claims
    WHERE entity_id = $1 AND claimant_user_id = $2
)
`

type UserIsClaimantForEntityParams struct {
	EntityID       uuid.UUID `json:"entity_id"`
	ClaimantUserID uuid.UUID `json:"claimant_user_id"`
}

func (q *Queries) UserIsClaimantForEntity(ctx context.Context, arg UserIsClaimantForEntityParams) (bool, error) {
	row := q.db.QueryRow(ctx, userIsClaimantForEntity, arg.EntityID, arg.ClaimantUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyEntityLegalID = `-- name: VerifyEntityLegalID :exec
UPDATE entity_legal_ids
SET is_verified = TRUE, verified_at = NOW(), updated_at = NOW()
WHERE entity_id = $1 AND id_type = $2
`

type VerifyEntityLegalIDParams struct {
	EntityID uuid.UUID `json:"entity_id"`
	IDType   string    `json:"id_type"`
}

func (q *Queries) VerifyEntityLegalID(ctx context.Context, arg VerifyEntityLegalIDParams) error {
	_, err := q.db.Exec(ctx, verifyEntityLegalID, arg.EntityID, arg.IDType)
	return err
}
