// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: document.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentsByWorkspace = `-- name: CountDocumentsByWorkspace :one
SELECT COUNT(*) FROM documents WHERE workspace_id = $1
`

func (q *Queries) CountDocumentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, workspace_id, document_type, file_key, file_name, file_size, mime_type,
    upload_status, extraction_status, verification_status, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, workspace_id, document_type, file_key, file_name, file_size, mime_type, upload_status, extraction_status, verification_status, extracted_data, extraction_confidence, extraction_error, transaction_id, created_by, uploaded_at, processed_at, created_at, updated_at
`

type CreateDocumentParams struct {
	ID                 uuid.UUID `json:"id"`
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	DocumentType       string    `json:"document_type"`
	FileKey            string    `json:"file_key"`
	FileName           string    `json:"file_name"`
	FileSize           int64     `json:"file_size"`
	MimeType           string    `json:"mime_type"`
	UploadStatus       string    `json:"upload_status"`
	ExtractionStatus   string    `json:"extraction_status"`
	VerificationStatus string    `json:"verification_status"`
	CreatedBy          uuid.UUID `json:"created_by"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.WorkspaceID,
		arg.DocumentType,
		arg.FileKey,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.UploadStatus,
		arg.ExtractionStatus,
		arg.VerificationStatus,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocumentType,
		&i.FileKey,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.UploadStatus,
		&i.ExtractionStatus,
		&i.VerificationStatus,
		&i.ExtractedData,
		&i.ExtractionConfidence,
		&i.ExtractionError,
		&i.TransactionID,
		&i.CreatedBy,
		&i.UploadedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, workspace_id, document_type, file_key, file_name, file_size, mime_type, upload_status, extraction_status, verification_status, extracted_data, extraction_confidence, extraction_error, transaction_id, created_by, uploaded_at, processed_at, created_at, updated_at FROM documents WHERE id = $1 AND workspace_id = $2
`

type GetDocumentByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.ID, arg.WorkspaceID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocumentType,
		&i.FileKey,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.UploadStatus,
		&i.ExtractionStatus,
		&i.VerificationStatus,
		&i.ExtractedData,
		&i.ExtractionConfidence,
		&i.ExtractionError,
		&i.TransactionID,
		&i.CreatedBy,
		&i.UploadedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkDocumentTransaction = `-- name: LinkDocumentTransaction :exec
UPDATE documents
SET transaction_id = $3, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type LinkDocumentTransactionParams struct {
	ID            uuid.UUID   `json:"id"`
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
}

func (q *Queries) LinkDocumentTransaction(ctx context.Context, arg LinkDocumentTransactionParams) error {
	_, err := q.db.Exec(ctx, linkDocumentTransaction, arg.ID, arg.WorkspaceID, arg.TransactionID)
	return err
}

const listDocumentsByWorkspace = `-- name: ListDocumentsByWorkspace :many
SELECT id, workspace_id, document_type, file_key, file_name, file_size, mime_type, upload_status, extraction_status, verification_status, extracted_data, extraction_confidence, extraction_error, transaction_id, created_by, uploaded_at, processed_at, created_at, updated_at FROM documents
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListDocumentsByWorkspace(ctx context.Context, arg ListDocumentsByWorkspaceParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocumentType,
			&i.FileKey,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.UploadStatus,
			&i.ExtractionStatus,
			&i.VerificationStatus,
			&i.ExtractedData,
			&i.ExtractionConfidence,
			&i.ExtractionError,
			&i.TransactionID,
			&i.CreatedBy,
			&i.UploadedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspaceDocumentUploaded = `-- name: MarkWorkspaceDocumentUploaded :exec
UPDATE documents
SET upload_status = 'UPLOADED', uploaded_at = NOW(), updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type MarkWorkspaceDocumentUploadedParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) MarkWorkspaceDocumentUploaded(ctx context.Context, arg MarkWorkspaceDocumentUploadedParams) error {
	_, err := q.db.Exec(ctx, markWorkspaceDocumentUploaded, arg.ID, arg.WorkspaceID)
	return err
}

const setDocumentExtractionProcessing = `-- name: SetDocumentExtractionProcessing :exec
UPDATE documents
SET extraction_status = 'PROCESSING', updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND extraction_status = 'PENDING'
`

type SetDocumentExtractionProcessingParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SetDocumentExtractionProcessing(ctx context.Context, arg SetDocumentExtractionProcessingParams) error {
	_, err := q.db.Exec(ctx, setDocumentExtractionProcessing, arg.ID, arg.WorkspaceID)
	return err
}

const updateDocumentExtraction = `-- name: UpdateDocumentExtraction :exec
UPDATE documents
SET extraction_status = $3,
    extracted_data = $4,
    extraction_confidence = $5,
    extraction_error = $6,
    processed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type UpdateDocumentExtractionParams struct {
	ID                   uuid.UUID      `json:"id"`
	WorkspaceID          uuid.UUID      `json:"workspace_id"`
	ExtractionStatus     string         `json:"extraction_status"`
	ExtractedData        []byte         `json:"extracted_data"`
	ExtractionConfidence pgtype.Numeric `json:"extraction_confidence"`
	ExtractionError      pgtype.Text    `json:"extraction_error"`
}

func (q *Queries) UpdateDocumentExtraction(ctx context.Context, arg UpdateDocumentExtractionParams) error {
	_, err := q.db.Exec(ctx, updateDocumentExtraction,
		arg.ID,
		arg.WorkspaceID,
		arg.ExtractionStatus,
		arg.ExtractedData,
		arg.ExtractionConfidence,
		arg.ExtractionError,
	)
	return err
}

const updateDocumentVerification = `-- name: UpdateDocumentVerification :exec
UPDATE documents
SET verification_status = $3, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type UpdateDocumentVerificationParams struct {
	ID                 uuid.UUID `json:"id"`
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	VerificationStatus string    `json:"verification_status"`
}

func (q *Queries) UpdateDocumentVerification(ctx context.Context, arg UpdateDocumentVerificationParams) error {
	_, err := q.db.Exec(ctx, updateDocumentVerification, arg.ID, arg.WorkspaceID, arg.VerificationStatus)
	return err
}
