// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entity.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (id, user_id, entity_type, nama_utama, nik_npwp, nomor_wa, alamat_lengkap, is_shadow, status, created_at, updated_at, nama_normalized)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, entity_type, nama_utama, nik_npwp, nomor_wa, alamat_lengkap, is_shadow, status, created_at, updated_at, nama_normalized
`

type CreateEntityParams struct {
	ID             uuid.UUID   `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	EntityType     string      `json:"entity_type"`
	NamaUtama      string      `json:"nama_utama"`
	NikNpwp        pgtype.Text `json:"nik_npwp"`
	NomorWa        pgtype.Text `json:"nomor_wa"`
	AlamatLengkap  pgtype.Text `json:"alamat_lengkap"`
	IsShadow       bool        `json:"is_shadow"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	NamaNormalized pgtype.Text `json:"nama_normalized"`
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.ID,
		arg.UserID,
		arg.EntityType,
		arg.NamaUtama,
		arg.NikNpwp,
		arg.NomorWa,
		arg.AlamatLengkap,
		arg.IsShadow,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.NamaNormalized,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.NamaUtama,
		&i.NikNpwp,
		&i.NomorWa,
		&i.AlamatLengkap,
		&i.IsShadow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamaNormalized,
	)
	return i, err
}

const createEntityMeta = `-- name: CreateEntityMeta :one
INSERT INTO entity_meta (id, entity_id, bidang_usaha, logo_url, website, email, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, entity_id, bidang_usaha, logo_url, website, email, description, created_at, updated_at
`

type CreateEntityMetaParams struct {
	ID          uuid.UUID   `json:"id"`
	EntityID    uuid.UUID   `json:"entity_id"`
	BidangUsaha pgtype.Text `json:"bidang_usaha"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Website     pgtype.Text `json:"website"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) CreateEntityMeta(ctx context.Context, arg CreateEntityMetaParams) (EntityMetum, error) {
	row := q.db.QueryRow(ctx, createEntityMeta,
		arg.ID,
		arg.EntityID,
		arg.BidangUsaha,
		arg.LogoUrl,
		arg.Website,
		arg.Email,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityMetum
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.BidangUsaha,
		&i.LogoUrl,
		&i.Website,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, user_id, entity_type, nama_utama, nik_npwp, nomor_wa, alamat_lengkap, is_shadow, status, created_at, updated_at, nama_normalized FROM entities WHERE id = $1
`

func (q *Queries) GetEntityByID(ctx context.Context, id uuid.UUID) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByID, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.NamaUtama,
		&i.NikNpwp,
		&i.NomorWa,
		&i.AlamatLengkap,
		&i.IsShadow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamaNormalized,
	)
	return i, err
}

const getEntityByUserID = `-- name: GetEntityByUserID :one
SELECT id, user_id, entity_type, nama_utama, nik_npwp, nomor_wa, alamat_lengkap, is_shadow, status, created_at, updated_at, nama_normalized FROM entities WHERE user_id = $1 AND entity_type = 'ORANG_PRIBADI' LIMIT 1
`

func (q *Queries) GetEntityByUserID(ctx context.Context, userID pgtype.UUID) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByUserID, userID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.NamaUtama,
		&i.NikNpwp,
		&i.NomorWa,
		&i.AlamatLengkap,
		&i.IsShadow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamaNormalized,
	)
	return i, err
}

const getEntityMetaByEntityID = `-- name: GetEntityMetaByEntityID :one
SELECT id, entity_id, bidang_usaha, logo_url, website, email, description, created_at, updated_at FROM entity_meta WHERE entity_id = $1
`

func (q *Queries) GetEntityMetaByEntityID(ctx context.Context, entityID uuid.UUID) (EntityMetum, error) {
	row := q.db.QueryRow(ctx, getEntityMetaByEntityID, entityID)
	var i EntityMetum
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.BidangUsaha,
		&i.LogoUrl,
		&i.Website,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntitiesByUserID = `-- name: ListEntitiesByUserID :many
SELECT id, user_id, entity_type, nama_utama, nik_npwp, nomor_wa, alamat_lengkap, is_shadow, status, created_at, updated_at, nama_normalized FROM entities WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEntitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.NamaUtama,
			&i.NikNpwp,
			&i.NomorWa,
			&i.AlamatLengkap,
			&i.IsShadow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaNormalized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEntitiesByName = `-- name: SearchEntitiesByName :many
SELECT id, user_id, entity_type, nama_utama, nik_npwp, nomor_wa, alamat_lengkap, is_shadow, status, created_at, updated_at, nama_normalized FROM entities
WHERE nama_utama ILIKE '%' || $1 || '%' AND status = 'ACTIVE'
ORDER BY nama_utama ASC
LIMIT $2 OFFSET $3
`

type SearchEntitiesByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchEntitiesByName(ctx context.Context, arg SearchEntitiesByNameParams) ([]Entity, error) {
	rows, err := q.db.Query(ctx, searchEntitiesByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.NamaUtama,
			&i.NikNpwp,
			&i.NomorWa,
			&i.AlamatLengkap,
			&i.IsShadow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaNormalized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntity = `-- name: UpdateEntity :exec
UPDATE entities
SET nama_utama = $2, nik_npwp = $3, nomor_wa = $4, alamat_lengkap = $5, nama_normalized = $6, updated_at = NOW()
WHERE id = $1
`

type UpdateEntityParams struct {
	ID             uuid.UUID   `json:"id"`
	NamaUtama      string      `json:"nama_utama"`
	NikNpwp        pgtype.Text `json:"nik_npwp"`
	NomorWa        pgtype.Text `json:"nomor_wa"`
	AlamatLengkap  pgtype.Text `json:"alamat_lengkap"`
	NamaNormalized pgtype.Text `json:"nama_normalized"`
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) error {
	_, err := q.db.Exec(ctx, updateEntity,
		arg.ID,
		arg.NamaUtama,
		arg.NikNpwp,
		arg.NomorWa,
		arg.AlamatLengkap,
		arg.NamaNormalized,
	)
	return err
}

const updateEntityMeta = `-- name: UpdateEntityMeta :exec
UPDATE entity_meta
SET bidang_usaha = $2, logo_url = $3, website = $4, email = $5, description = $6, updated_at = NOW()
WHERE entity_id = $1
`

type UpdateEntityMetaParams struct {
	EntityID    uuid.UUID   `json:"entity_id"`
	BidangUsaha pgtype.Text `json:"bidang_usaha"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Website     pgtype.Text `json:"website"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateEntityMeta(ctx context.Context, arg UpdateEntityMetaParams) error {
	_, err := q.db.Exec(ctx, updateEntityMeta,
		arg.EntityID,
		arg.BidangUsaha,
		arg.LogoUrl,
		arg.Website,
		arg.Email,
		arg.Description,
	)
	return err
}

const updateEntityStatus = `-- name: UpdateEntityStatus :exec
UPDATE entities SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateEntityStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEntityStatus(ctx context.Context, arg UpdateEntityStatusParams) error {
	_, err := q.db.Exec(ctx, updateEntityStatus, arg.ID, arg.Status)
	return err
}

const upsertEntityMeta = `-- name: UpsertEntityMeta :one
INSERT INTO entity_meta (id, entity_id, bidang_usaha, logo_url, website, email, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (entity_id)
DO UPDATE SET bidang_usaha = EXCLUDED.bidang_usaha, logo_url = EXCLUDED.logo_url, website = EXCLUDED.website, email = EXCLUDED.email, description = EXCLUDED.description, updated_at = NOW()
RETURNING id, entity_id, bidang_usaha, logo_url, website, email, description, created_at, updated_at
`

type UpsertEntityMetaParams struct {
	ID          uuid.UUID   `json:"id"`
	EntityID    uuid.UUID   `json:"entity_id"`
	BidangUsaha pgtype.Text `json:"bidang_usaha"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Website     pgtype.Text `json:"website"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) UpsertEntityMeta(ctx context.Context, arg UpsertEntityMetaParams) (EntityMetum, error) {
	row := q.db.QueryRow(ctx, upsertEntityMeta,
		arg.ID,
		arg.EntityID,
		arg.BidangUsaha,
		arg.LogoUrl,
		arg.Website,
		arg.Email,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityMetum
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.BidangUsaha,
		&i.LogoUrl,
		&i.Website,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userCanViewEntityAsCounterparty = `-- name: UserCanViewEntityAsCounterparty :one
SELECT EXISTS(
    SELECT 1 FROM entity_relations cp
    JOIN entity_relations member ON member.object_id = cp.object_id
    JOIN entities pe ON pe.id = member.subject_id
    WHERE cp.subject_id = $1
      AND pe.user_id = $2
      AND cp.relation_type IN ('PELANGGAN', 'VENDOR')
      AND member.relation_type IN ('PEMILIK', 'KARYAWAN')
      AND cp.status = 'ACTIVE'
      AND member.status = 'ACTIVE'
)
`

type UserCanViewEntityAsCounterpartyParams struct {
	SubjectID uuid.UUID   `json:"subject_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UserCanViewEntityAsCounterparty(ctx context.Context, arg UserCanViewEntityAsCounterpartyParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanViewEntityAsCounterparty, arg.SubjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userCanViewEntityAsWorkspaceMember = `-- name: UserCanViewEntityAsWorkspaceMember :one
SELECT EXISTS(
    SELECT 1 FROM entity_relations er
    JOIN entities pe ON pe.id = er.subject_id
    WHERE er.object_id = $1
      AND pe.user_id = $2
      AND er.relation_type IN ('PEMILIK', 'KARYAWAN')
      AND er.status = 'ACTIVE'
)
`

type UserCanViewEntityAsWorkspaceMemberParams struct {
	ObjectID uuid.UUID   `json:"object_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UserCanViewEntityAsWorkspaceMember(ctx context.Context, arg UserCanViewEntityAsWorkspaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanViewEntityAsWorkspaceMember, arg.ObjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
