// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupConsumedEvents = `-- name: CleanupConsumedEvents :exec
DELETE FROM inbox_consumed_events WHERE processed_at < $1
`

func (q *Queries) CleanupConsumedEvents(ctx context.Context, processedAt time.Time) error {
	_, err := q.db.Exec(ctx, cleanupConsumedEvents, processedAt)
	return err
}

const cleanupPublishedEvents = `-- name: CleanupPublishedEvents :exec
DELETE FROM outbox_events WHERE status = 'published' AND published_at < $1
`

func (q *Queries) CleanupPublishedEvents(ctx context.Context, publishedAt *time.Time) error {
	_, err := q.db.Exec(ctx, cleanupPublishedEvents, publishedAt)
	return err
}

const countPendingOutboxEvents = `-- name: CountPendingOutboxEvents :one
SELECT COUNT(*) FROM outbox_events WHERE status = 'pending'
`

func (q *Queries) CountPendingOutboxEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOutboxEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (id, event_type, event_version, workspace_id, actor_id, correlation_id, causation_id, idempotency_key, payload, metadata, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'pending', $11)
RETURNING id, event_type, event_version, workspace_id, actor_id, correlation_id, causation_id, idempotency_key, payload, metadata, status, published_at, retry_count, max_retries, next_retry_at, error_message, created_at
`

type CreateOutboxEventParams struct {
	ID             uuid.UUID   `json:"id"`
	EventType      string      `json:"event_type"`
	EventVersion   int32       `json:"event_version"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ActorID        pgtype.UUID `json:"actor_id"`
	CorrelationID  uuid.UUID   `json:"correlation_id"`
	CausationID    pgtype.UUID `json:"causation_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Payload        []byte      `json:"payload"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.EventVersion,
		arg.WorkspaceID,
		arg.ActorID,
		arg.CorrelationID,
		arg.CausationID,
		arg.IdempotencyKey,
		arg.Payload,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.EventVersion,
		&i.WorkspaceID,
		&i.ActorID,
		&i.CorrelationID,
		&i.CausationID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Metadata,
		&i.Status,
		&i.PublishedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getOutboxEventByID = `-- name: GetOutboxEventByID :one
SELECT id, event_type, event_version, workspace_id, actor_id, correlation_id, causation_id, idempotency_key, payload, metadata, status, published_at, retry_count, max_retries, next_retry_at, error_message, created_at FROM outbox_events WHERE id = $1
`

func (q *Queries) GetOutboxEventByID(ctx context.Context, id uuid.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByID, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.EventVersion,
		&i.WorkspaceID,
		&i.ActorID,
		&i.CorrelationID,
		&i.CausationID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Metadata,
		&i.Status,
		&i.PublishedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, event_version, workspace_id, actor_id, correlation_id, causation_id, idempotency_key, payload, metadata, status, published_at, retry_count, max_retries, next_retry_at, error_message, created_at FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EventVersion,
			&i.WorkspaceID,
			&i.ActorID,
			&i.CorrelationID,
			&i.CausationID,
			&i.IdempotencyKey,
			&i.Payload,
			&i.Metadata,
			&i.Status,
			&i.PublishedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetryableOutboxEvents = `-- name: GetRetryableOutboxEvents :many
SELECT id, event_type, event_version, workspace_id, actor_id, correlation_id, causation_id, idempotency_key, payload, metadata, status, published_at, retry_count, max_retries, next_retry_at, error_message, created_at FROM outbox_events
WHERE status = 'failed' AND retry_count < max_retries AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetRetryableOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getRetryableOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EventVersion,
			&i.WorkspaceID,
			&i.ActorID,
			&i.CorrelationID,
			&i.CausationID,
			&i.IdempotencyKey,
			&i.Payload,
			&i.Metadata,
			&i.Status,
			&i.PublishedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEventConsumed = `-- name: IsEventConsumed :one
SELECT EXISTS(SELECT 1 FROM inbox_consumed_events WHERE event_id = $1 AND consumer_name = $2)
`

type IsEventConsumedParams struct {
	EventID      uuid.UUID `json:"event_id"`
	ConsumerName string    `json:"consumer_name"`
}

func (q *Queries) IsEventConsumed(ctx context.Context, arg IsEventConsumedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventConsumed, arg.EventID, arg.ConsumerName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEventConsumed = `-- name: MarkEventConsumed :exec
INSERT INTO inbox_consumed_events (id, event_id, consumer_name, processed_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (event_id, consumer_name) DO NOTHING
`

type MarkEventConsumedParams struct {
	ID           uuid.UUID `json:"id"`
	EventID      uuid.UUID `json:"event_id"`
	ConsumerName string    `json:"consumer_name"`
}

func (q *Queries) MarkEventConsumed(ctx context.Context, arg MarkEventConsumedParams) error {
	_, err := q.db.Exec(ctx, markEventConsumed, arg.ID, arg.EventID, arg.ConsumerName)
	return err
}

const markOutboxEventDLQ = `-- name: MarkOutboxEventDLQ :exec
UPDATE outbox_events SET status = 'dlq', error_message = $2 WHERE id = $1
`

type MarkOutboxEventDLQParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkOutboxEventDLQ(ctx context.Context, arg MarkOutboxEventDLQParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventDLQ, arg.ID, arg.ErrorMessage)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET status = 'failed', retry_count = retry_count + 1, error_message = $2, next_retry_at = $3
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
	NextRetryAt  *time.Time  `json:"next_retry_at"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.ErrorMessage, arg.NextRetryAt)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events SET status = 'published', published_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
