// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invite.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE workspace_invites SET accepted_at = NOW() WHERE id = $1
`

func (q *Queries) AcceptInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvite, id)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO workspace_invites (id, workspace_id, invited_email, role_id, token, invited_by, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, invited_email, role_id, token, invited_by, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	ID           uuid.UUID `json:"id"`
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	InvitedEmail string    `json:"invited_email"`
	RoleID       uuid.UUID `json:"role_id"`
	Token        string    `json:"token"`
	InvitedBy    uuid.UUID `json:"invited_by"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.InvitedEmail,
		arg.RoleID,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedEmail,
		&i.RoleID,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM workspace_invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT id, workspace_id, invited_email, role_id, token, invited_by, expires_at, accepted_at, created_at FROM workspace_invites WHERE id = $1
`

func (q *Queries) GetInviteByID(ctx context.Context, id uuid.UUID) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByID, id)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedEmail,
		&i.RoleID,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, workspace_id, invited_email, role_id, token, invited_by, expires_at, accepted_at, created_at FROM workspace_invites WHERE token = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedEmail,
		&i.RoleID,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitesByWorkspace = `-- name: ListPendingInvitesByWorkspace :many
SELECT id, workspace_id, invited_email, role_id, token, invited_by, expires_at, accepted_at, created_at FROM workspace_invites
WHERE workspace_id = $1 AND accepted_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvite{}
	for rows.Next() {
		var i WorkspaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InvitedEmail,
			&i.RoleID,
			&i.Token,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
