// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           uuid.UUID   `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	EventType    string      `json:"event_type"`
	EventData    []byte      `json:"event_data"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Success      bool        `json:"success"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreatedAt    time.Time   `json:"created_at"`
}

type OtpCode struct {
	ID             uuid.UUID  `json:"id"`
	Identifier     string     `json:"identifier"`
	IdentifierType string     `json:"identifier_type"`
	Code           string     `json:"code"`
	Purpose        string     `json:"purpose"`
	Attempts       int32      `json:"attempts"`
	MaxAttempts    int32      `json:"max_attempts"`
	ExpiresAt      time.Time  `json:"expires_at"`
	UsedAt         *time.Time `json:"used_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type Plan struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  pgtype.Text    `json:"description"`
	Type         string         `json:"type"`
	PriceMonthly pgtype.Numeric `json:"price_monthly"`
	PriceYearly  pgtype.Numeric `json:"price_yearly"`
	IsTrial      bool           `json:"is_trial"`
	TrialDays    int32          `json:"trial_days"`
	Tier         int32          `json:"tier"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type PlanFeature struct {
	ID          uuid.UUID   `json:"id"`
	PlanID      uuid.UUID   `json:"plan_id"`
	FeatureKey  string      `json:"feature_key"`
	FeatureType string      `json:"feature_type"`
	ValueBool   pgtype.Bool `json:"value_bool"`
	ValueInt    pgtype.Int4 `json:"value_int"`
	ValueText   pgtype.Text `json:"value_text"`
	CreatedAt   time.Time   `json:"created_at"`
}

type PlatformAdmin struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Role         string      `json:"role"`
	MfaSecret    pgtype.Text `json:"mfa_secret"`
	MfaEnabled   bool        `json:"mfa_enabled"`
	Status       string      `json:"status"`
	LastLoginAt  *time.Time  `json:"last_login_at"`
	LastLoginIp  *netip.Addr `json:"last_login_ip"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	RefreshToken string      `json:"refresh_token"`
	DeviceName   pgtype.Text `json:"device_name"`
	DeviceType   pgtype.Text `json:"device_type"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	ExpiresAt    time.Time   `json:"expires_at"`
	LastUsedAt   time.Time   `json:"last_used_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type User struct {
	ID               uuid.UUID   `json:"id"`
	Email            pgtype.Text `json:"email"`
	Whatsapp         pgtype.Text `json:"whatsapp"`
	PasswordHash     pgtype.Text `json:"password_hash"`
	EmailVerified    bool        `json:"email_verified"`
	WhatsappVerified bool        `json:"whatsapp_verified"`
	Status           string      `json:"status"`
	LastLoginAt      *time.Time  `json:"last_login_at"`
	LastLoginIp      *netip.Addr `json:"last_login_ip"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Name             pgtype.Text `json:"name"`
}
