// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            uuid.UUID   `json:"id"`
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	AccountType   string      `json:"account_type"`
	NormalBalance string      `json:"normal_balance"`
	Level         int32       `json:"level"`
	IsSystem      bool        `json:"is_system"`
	IsActive      bool        `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type AccountBalance struct {
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	AccountID        uuid.UUID      `json:"account_id"`
	Period           string         `json:"period"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
	EndingBalance    pgtype.Numeric `json:"ending_balance"`
	TransactionCount int32          `json:"transaction_count"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type AuditLog struct {
	ID           uuid.UUID   `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	EventType    string      `json:"event_type"`
	EventData    []byte      `json:"event_data"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Success      bool        `json:"success"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreatedAt    time.Time   `json:"created_at"`
}

type ClaimAuditLog struct {
	ID        uuid.UUID   `json:"id"`
	ClaimID   uuid.UUID   `json:"claim_id"`
	ActorID   uuid.UUID   `json:"actor_id"`
	ActorType string      `json:"actor_type"`
	Action    string      `json:"action"`
	OldStatus pgtype.Text `json:"old_status"`
	NewStatus pgtype.Text `json:"new_status"`
	Details   []byte      `json:"details"`
	CreatedAt time.Time   `json:"created_at"`
}

type ClaimDocument struct {
	ID           uuid.UUID  `json:"id"`
	ClaimID      uuid.UUID  `json:"claim_id"`
	DocumentType string     `json:"document_type"`
	FileKey      string     `json:"file_key"`
	FileName     string     `json:"file_name"`
	FileSize     int64      `json:"file_size"`
	MimeType     string     `json:"mime_type"`
	UploadStatus string     `json:"upload_status"`
	UploadedAt   *time.Time `json:"uploaded_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type CompanyClaim struct {
	ID               uuid.UUID   `json:"id"`
	EntityID         uuid.UUID   `json:"entity_id"`
	ClaimantUserID   uuid.UUID   `json:"claimant_user_id"`
	ClaimantEntityID uuid.UUID   `json:"claimant_entity_id"`
	Status           string      `json:"status"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
	ReviewedAt       *time.Time  `json:"reviewed_at"`
	RejectionReason  pgtype.Text `json:"rejection_reason"`
	DisputeReason    pgtype.Text `json:"dispute_reason"`
	Notes            pgtype.Text `json:"notes"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type CounterpartyAlias struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	EntityID    uuid.UUID `json:"entity_id"`
	CustomAlias string    `json:"custom_alias"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Document struct {
	ID                   uuid.UUID      `json:"id"`
	WorkspaceID          uuid.UUID      `json:"workspace_id"`
	DocumentType         string         `json:"document_type"`
	FileKey              string         `json:"file_key"`
	FileName             string         `json:"file_name"`
	FileSize             int64          `json:"file_size"`
	MimeType             string         `json:"mime_type"`
	UploadStatus         string         `json:"upload_status"`
	ExtractionStatus     string         `json:"extraction_status"`
	VerificationStatus   string         `json:"verification_status"`
	ExtractedData        []byte         `json:"extracted_data"`
	ExtractionConfidence pgtype.Numeric `json:"extraction_confidence"`
	ExtractionError      pgtype.Text    `json:"extraction_error"`
	TransactionID        pgtype.UUID    `json:"transaction_id"`
	CreatedBy            uuid.UUID      `json:"created_by"`
	UploadedAt           *time.Time     `json:"uploaded_at"`
	ProcessedAt          *time.Time     `json:"processed_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type Entity struct {
	ID             uuid.UUID   `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	EntityType     string      `json:"entity_type"`
	NamaUtama      string      `json:"nama_utama"`
	NikNpwp        pgtype.Text `json:"nik_npwp"`
	NomorWa        pgtype.Text `json:"nomor_wa"`
	AlamatLengkap  pgtype.Text `json:"alamat_lengkap"`
	IsShadow       bool        `json:"is_shadow"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	NamaNormalized pgtype.Text `json:"nama_normalized"`
}

type EntityAlias struct {
	ID              uuid.UUID `json:"id"`
	EntityID        uuid.UUID `json:"entity_id"`
	Alias           string    `json:"alias"`
	AliasNormalized string    `json:"alias_normalized"`
	Source          string    `json:"source"`
	CreatedAt       time.Time `json:"created_at"`
}

type EntityLegalID struct {
	ID         uuid.UUID  `json:"id"`
	EntityID   uuid.UUID  `json:"entity_id"`
	IDType     string     `json:"id_type"`
	IDValue    string     `json:"id_value"`
	IsVerified bool       `json:"is_verified"`
	VerifiedAt *time.Time `json:"verified_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type EntityMetum struct {
	ID          uuid.UUID   `json:"id"`
	EntityID    uuid.UUID   `json:"entity_id"`
	BidangUsaha pgtype.Text `json:"bidang_usaha"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Website     pgtype.Text `json:"website"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type EntityRelation struct {
	ID           uuid.UUID   `json:"id"`
	ObjectID     uuid.UUID   `json:"object_id"`
	SubjectID    uuid.UUID   `json:"subject_id"`
	RelationType string      `json:"relation_type"`
	CustomAlias  pgtype.Text `json:"custom_alias"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type EntityVerification struct {
	ID              uuid.UUID   `json:"id"`
	EntityID        uuid.UUID   `json:"entity_id"`
	Status          string      `json:"status"`
	VerifiedBy      pgtype.UUID `json:"verified_by"`
	VerifiedAt      *time.Time  `json:"verified_at"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	Notes           pgtype.Text `json:"notes"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type InboxConsumedEvent struct {
	ID           uuid.UUID `json:"id"`
	EventID      uuid.UUID `json:"event_id"`
	ConsumerName string    `json:"consumer_name"`
	ProcessedAt  time.Time `json:"processed_at"`
}

type Invoice struct {
	ID             uuid.UUID      `json:"id"`
	WorkspaceID    uuid.UUID      `json:"workspace_id"`
	SubscriptionID uuid.UUID      `json:"subscription_id"`
	InvoiceNumber  string         `json:"invoice_number"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Status         string         `json:"status"`
	Description    pgtype.Text    `json:"description"`
	DueDate        time.Time      `json:"due_date"`
	PaidAt         *time.Time     `json:"paid_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Item struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Name        string         `json:"name"`
	ItemType    string         `json:"item_type"`
	Unit        string         `json:"unit"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	AccountID   pgtype.UUID    `json:"account_id"`
	Description pgtype.Text    `json:"description"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type JournalEntry struct {
	ID            uuid.UUID      `json:"id"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Description   pgtype.Text    `json:"description"`
	Debit         pgtype.Numeric `json:"debit"`
	Credit        pgtype.Numeric `json:"credit"`
	SortOrder     int32          `json:"sort_order"`
	CreatedAt     time.Time      `json:"created_at"`
}

type LedgerEntry struct {
	ID              uuid.UUID      `json:"id"`
	WorkspaceID     uuid.UUID      `json:"workspace_id"`
	AccountID       uuid.UUID      `json:"account_id"`
	JournalEntryID  uuid.UUID      `json:"journal_entry_id"`
	TransactionID   uuid.UUID      `json:"transaction_id"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	Debit           pgtype.Numeric `json:"debit"`
	Credit          pgtype.Numeric `json:"credit"`
	RunningBalance  pgtype.Numeric `json:"running_balance"`
	PostedAt        time.Time      `json:"posted_at"`
}

type OtpCode struct {
	ID             uuid.UUID  `json:"id"`
	Identifier     string     `json:"identifier"`
	IdentifierType string     `json:"identifier_type"`
	Code           string     `json:"code"`
	Purpose        string     `json:"purpose"`
	Attempts       int32      `json:"attempts"`
	MaxAttempts    int32      `json:"max_attempts"`
	ExpiresAt      time.Time  `json:"expires_at"`
	UsedAt         *time.Time `json:"used_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type OutboxEvent struct {
	ID             uuid.UUID   `json:"id"`
	EventType      string      `json:"event_type"`
	EventVersion   int32       `json:"event_version"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ActorID        pgtype.UUID `json:"actor_id"`
	CorrelationID  uuid.UUID   `json:"correlation_id"`
	CausationID    pgtype.UUID `json:"causation_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Payload        []byte      `json:"payload"`
	Metadata       []byte      `json:"metadata"`
	Status         string      `json:"status"`
	PublishedAt    *time.Time  `json:"published_at"`
	RetryCount     int32       `json:"retry_count"`
	MaxRetries     int32       `json:"max_retries"`
	NextRetryAt    *time.Time  `json:"next_retry_at"`
	ErrorMessage   pgtype.Text `json:"error_message"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Payment struct {
	ID                 uuid.UUID      `json:"id"`
	InvoiceID          uuid.UUID      `json:"invoice_id"`
	WorkspaceID        uuid.UUID      `json:"workspace_id"`
	XenditInvoiceID    pgtype.Text    `json:"xendit_invoice_id"`
	XenditPaymentUrl   pgtype.Text    `json:"xendit_payment_url"`
	Amount             pgtype.Numeric `json:"amount"`
	Currency           string         `json:"currency"`
	Status             string         `json:"status"`
	PaymentMethod      pgtype.Text    `json:"payment_method"`
	PaidAt             *time.Time     `json:"paid_at"`
	ExpiredAt          *time.Time     `json:"expired_at"`
	FailureReason      pgtype.Text    `json:"failure_reason"`
	XenditCallbackData []byte         `json:"xendit_callback_data"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Plan struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  pgtype.Text    `json:"description"`
	Type         string         `json:"type"`
	PriceMonthly pgtype.Numeric `json:"price_monthly"`
	PriceYearly  pgtype.Numeric `json:"price_yearly"`
	IsTrial      bool           `json:"is_trial"`
	TrialDays    int32          `json:"trial_days"`
	Tier         int32          `json:"tier"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type PlanFeature struct {
	ID          uuid.UUID   `json:"id"`
	PlanID      uuid.UUID   `json:"plan_id"`
	FeatureKey  string      `json:"feature_key"`
	FeatureType string      `json:"feature_type"`
	ValueBool   pgtype.Bool `json:"value_bool"`
	ValueInt    pgtype.Int4 `json:"value_int"`
	ValueText   pgtype.Text `json:"value_text"`
	CreatedAt   time.Time   `json:"created_at"`
}

type PlatformAdmin struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Role         string      `json:"role"`
	MfaSecret    pgtype.Text `json:"mfa_secret"`
	MfaEnabled   bool        `json:"mfa_enabled"`
	Status       string      `json:"status"`
	LastLoginAt  *time.Time  `json:"last_login_at"`
	LastLoginIp  *netip.Addr `json:"last_login_ip"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	RefreshToken string      `json:"refresh_token"`
	DeviceName   pgtype.Text `json:"device_name"`
	DeviceType   pgtype.Text `json:"device_type"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	ExpiresAt    time.Time   `json:"expires_at"`
	LastUsedAt   time.Time   `json:"last_used_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type TenantSubscription struct {
	ID           uuid.UUID   `json:"id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	PlanID       uuid.UUID   `json:"plan_id"`
	Status       string      `json:"status"`
	BillingCycle pgtype.Text `json:"billing_cycle"`
	StartedAt    time.Time   `json:"started_at"`
	ExpiresAt    *time.Time  `json:"expires_at"`
	TrialEndsAt  *time.Time  `json:"trial_ends_at"`
	CancelledAt  *time.Time  `json:"cancelled_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type TenantUsage struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureKey  string    `json:"feature_key"`
	UsageCount  int32     `json:"usage_count"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Transaction struct {
	ID                    uuid.UUID      `json:"id"`
	WorkspaceID           uuid.UUID      `json:"workspace_id"`
	TransactionNumber     string         `json:"transaction_number"`
	TransactionType       string         `json:"transaction_type"`
	InputMode             string         `json:"input_mode"`
	Status                string         `json:"status"`
	CounterpartyEntityID  pgtype.UUID    `json:"counterparty_entity_id"`
	CounterpartyName      pgtype.Text    `json:"counterparty_name"`
	Description           pgtype.Text    `json:"description"`
	TransactionDate       pgtype.Date    `json:"transaction_date"`
	Amount                pgtype.Numeric `json:"amount"`
	Currency              string         `json:"currency"`
	Category              pgtype.Text    `json:"category"`
	AiConfidence          pgtype.Numeric `json:"ai_confidence"`
	PaymentMethod         pgtype.Text    `json:"payment_method"`
	IncludesTax           bool           `json:"includes_tax"`
	TaxAmount             pgtype.Numeric `json:"tax_amount"`
	ReversedTransactionID pgtype.UUID    `json:"reversed_transaction_id"`
	CreatedBy             uuid.UUID      `json:"created_by"`
	PostedAt              *time.Time     `json:"posted_at"`
	VoidedAt              *time.Time     `json:"voided_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type TransactionLineItem struct {
	ID             uuid.UUID      `json:"id"`
	TransactionID  uuid.UUID      `json:"transaction_id"`
	WorkspaceID    uuid.UUID      `json:"workspace_id"`
	ItemID         pgtype.UUID    `json:"item_id"`
	Description    string         `json:"description"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	LineTotal      pgtype.Numeric `json:"line_total"`
	SortOrder      int32          `json:"sort_order"`
	CreatedAt      time.Time      `json:"created_at"`
}

type User struct {
	ID               uuid.UUID   `json:"id"`
	Email            pgtype.Text `json:"email"`
	Whatsapp         pgtype.Text `json:"whatsapp"`
	PasswordHash     pgtype.Text `json:"password_hash"`
	EmailVerified    bool        `json:"email_verified"`
	WhatsappVerified bool        `json:"whatsapp_verified"`
	Status           string      `json:"status"`
	LastLoginAt      *time.Time  `json:"last_login_at"`
	LastLoginIp      *netip.Addr `json:"last_login_ip"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Name             pgtype.Text `json:"name"`
}

type WorkspaceInvite struct {
	ID           uuid.UUID  `json:"id"`
	WorkspaceID  uuid.UUID  `json:"workspace_id"`
	InvitedEmail string     `json:"invited_email"`
	RoleID       uuid.UUID  `json:"role_id"`
	Token        string     `json:"token"`
	InvitedBy    uuid.UUID  `json:"invited_by"`
	ExpiresAt    time.Time  `json:"expires_at"`
	AcceptedAt   *time.Time `json:"accepted_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type WorkspaceRole struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Permissions []string    `json:"permissions"`
	IsSystem    bool        `json:"is_system"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type WorkspaceRoleAssignment struct {
	ID             uuid.UUID `json:"id"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
	RoleID         uuid.UUID `json:"role_id"`
	AssignedBy     uuid.UUID `json:"assigned_by"`
	CreatedAt      time.Time `json:"created_at"`
}
