// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           uuid.UUID   `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	EventType    string      `json:"event_type"`
	EventData    []byte      `json:"event_data"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Success      bool        `json:"success"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Entity struct {
	ID            uuid.UUID   `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	EntityType    string      `json:"entity_type"`
	NamaUtama     string      `json:"nama_utama"`
	NikNpwp       pgtype.Text `json:"nik_npwp"`
	NomorWa       pgtype.Text `json:"nomor_wa"`
	AlamatLengkap pgtype.Text `json:"alamat_lengkap"`
	IsShadow      bool        `json:"is_shadow"`
	Status        string      `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type EntityMetum struct {
	ID          uuid.UUID   `json:"id"`
	EntityID    uuid.UUID   `json:"entity_id"`
	BidangUsaha pgtype.Text `json:"bidang_usaha"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Website     pgtype.Text `json:"website"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type EntityRelation struct {
	ID           uuid.UUID   `json:"id"`
	ObjectID     uuid.UUID   `json:"object_id"`
	SubjectID    uuid.UUID   `json:"subject_id"`
	RelationType string      `json:"relation_type"`
	CustomAlias  pgtype.Text `json:"custom_alias"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type InboxConsumedEvent struct {
	ID           uuid.UUID `json:"id"`
	EventID      uuid.UUID `json:"event_id"`
	ConsumerName string    `json:"consumer_name"`
	ProcessedAt  time.Time `json:"processed_at"`
}

type Invoice struct {
	ID             uuid.UUID      `json:"id"`
	WorkspaceID    uuid.UUID      `json:"workspace_id"`
	SubscriptionID uuid.UUID      `json:"subscription_id"`
	InvoiceNumber  string         `json:"invoice_number"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Status         string         `json:"status"`
	Description    pgtype.Text    `json:"description"`
	DueDate        time.Time      `json:"due_date"`
	PaidAt         *time.Time     `json:"paid_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type OtpCode struct {
	ID             uuid.UUID  `json:"id"`
	Identifier     string     `json:"identifier"`
	IdentifierType string     `json:"identifier_type"`
	Code           string     `json:"code"`
	Purpose        string     `json:"purpose"`
	Attempts       int32      `json:"attempts"`
	MaxAttempts    int32      `json:"max_attempts"`
	ExpiresAt      time.Time  `json:"expires_at"`
	UsedAt         *time.Time `json:"used_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type OutboxEvent struct {
	ID             uuid.UUID   `json:"id"`
	EventType      string      `json:"event_type"`
	EventVersion   int32       `json:"event_version"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ActorID        pgtype.UUID `json:"actor_id"`
	CorrelationID  uuid.UUID   `json:"correlation_id"`
	CausationID    pgtype.UUID `json:"causation_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Payload        []byte      `json:"payload"`
	Metadata       []byte      `json:"metadata"`
	Status         string      `json:"status"`
	PublishedAt    *time.Time  `json:"published_at"`
	RetryCount     int32       `json:"retry_count"`
	MaxRetries     int32       `json:"max_retries"`
	NextRetryAt    *time.Time  `json:"next_retry_at"`
	ErrorMessage   pgtype.Text `json:"error_message"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Payment struct {
	ID                 uuid.UUID      `json:"id"`
	InvoiceID          uuid.UUID      `json:"invoice_id"`
	WorkspaceID        uuid.UUID      `json:"workspace_id"`
	XenditInvoiceID    pgtype.Text    `json:"xendit_invoice_id"`
	XenditPaymentUrl   pgtype.Text    `json:"xendit_payment_url"`
	Amount             pgtype.Numeric `json:"amount"`
	Currency           string         `json:"currency"`
	Status             string         `json:"status"`
	PaymentMethod      pgtype.Text    `json:"payment_method"`
	PaidAt             *time.Time     `json:"paid_at"`
	ExpiredAt          *time.Time     `json:"expired_at"`
	FailureReason      pgtype.Text    `json:"failure_reason"`
	XenditCallbackData []byte         `json:"xendit_callback_data"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Plan struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  pgtype.Text    `json:"description"`
	Type         string         `json:"type"`
	PriceMonthly pgtype.Numeric `json:"price_monthly"`
	PriceYearly  pgtype.Numeric `json:"price_yearly"`
	IsTrial      bool           `json:"is_trial"`
	TrialDays    int32          `json:"trial_days"`
	Tier         int32          `json:"tier"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type PlanFeature struct {
	ID          uuid.UUID   `json:"id"`
	PlanID      uuid.UUID   `json:"plan_id"`
	FeatureKey  string      `json:"feature_key"`
	FeatureType string      `json:"feature_type"`
	ValueBool   pgtype.Bool `json:"value_bool"`
	ValueInt    pgtype.Int4 `json:"value_int"`
	ValueText   pgtype.Text `json:"value_text"`
	CreatedAt   time.Time   `json:"created_at"`
}

type PlatformAdmin struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Role         string      `json:"role"`
	MfaSecret    pgtype.Text `json:"mfa_secret"`
	MfaEnabled   bool        `json:"mfa_enabled"`
	Status       string      `json:"status"`
	LastLoginAt  *time.Time  `json:"last_login_at"`
	LastLoginIp  *netip.Addr `json:"last_login_ip"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	RefreshToken string      `json:"refresh_token"`
	DeviceName   pgtype.Text `json:"device_name"`
	DeviceType   pgtype.Text `json:"device_type"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	ExpiresAt    time.Time   `json:"expires_at"`
	LastUsedAt   time.Time   `json:"last_used_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type TenantSubscription struct {
	ID           uuid.UUID   `json:"id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	PlanID       uuid.UUID   `json:"plan_id"`
	Status       string      `json:"status"`
	BillingCycle pgtype.Text `json:"billing_cycle"`
	StartedAt    time.Time   `json:"started_at"`
	ExpiresAt    *time.Time  `json:"expires_at"`
	TrialEndsAt  *time.Time  `json:"trial_ends_at"`
	CancelledAt  *time.Time  `json:"cancelled_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type TenantUsage struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureKey  string    `json:"feature_key"`
	UsageCount  int32     `json:"usage_count"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID               uuid.UUID   `json:"id"`
	Email            pgtype.Text `json:"email"`
	Whatsapp         pgtype.Text `json:"whatsapp"`
	PasswordHash     pgtype.Text `json:"password_hash"`
	EmailVerified    bool        `json:"email_verified"`
	WhatsappVerified bool        `json:"whatsapp_verified"`
	Status           string      `json:"status"`
	LastLoginAt      *time.Time  `json:"last_login_at"`
	LastLoginIp      *netip.Addr `json:"last_login_ip"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Name             pgtype.Text `json:"name"`
}

type WorkspaceInvite struct {
	ID           uuid.UUID  `json:"id"`
	WorkspaceID  uuid.UUID  `json:"workspace_id"`
	InvitedEmail string     `json:"invited_email"`
	RoleID       uuid.UUID  `json:"role_id"`
	Token        string     `json:"token"`
	InvitedBy    uuid.UUID  `json:"invited_by"`
	ExpiresAt    time.Time  `json:"expires_at"`
	AcceptedAt   *time.Time `json:"accepted_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type WorkspaceRole struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Permissions []string    `json:"permissions"`
	IsSystem    bool        `json:"is_system"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type WorkspaceRoleAssignment struct {
	ID             uuid.UUID `json:"id"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
	RoleID         uuid.UUID `json:"role_id"`
	AssignedBy     uuid.UUID `json:"assigned_by"`
	CreatedAt      time.Time `json:"created_at"`
}
