// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plan.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (id, name, slug, description, type, price_monthly, price_yearly, is_trial, trial_days, tier, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, name, slug, description, type, price_monthly, price_yearly, is_trial, trial_days, tier, is_active, created_at, updated_at
`

type CreatePlanParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  pgtype.Text    `json:"description"`
	Type         string         `json:"type"`
	PriceMonthly pgtype.Numeric `json:"price_monthly"`
	PriceYearly  pgtype.Numeric `json:"price_yearly"`
	IsTrial      bool           `json:"is_trial"`
	TrialDays    int32          `json:"trial_days"`
	Tier         int32          `json:"tier"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Type,
		arg.PriceMonthly,
		arg.PriceYearly,
		arg.IsTrial,
		arg.TrialDays,
		arg.Tier,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.IsTrial,
		&i.TrialDays,
		&i.Tier,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlanFeature = `-- name: CreatePlanFeature :one
INSERT INTO plan_features (id, plan_id, feature_key, feature_type, value_bool, value_int, value_text, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, plan_id, feature_key, feature_type, value_bool, value_int, value_text, created_at
`

type CreatePlanFeatureParams struct {
	ID          uuid.UUID   `json:"id"`
	PlanID      uuid.UUID   `json:"plan_id"`
	FeatureKey  string      `json:"feature_key"`
	FeatureType string      `json:"feature_type"`
	ValueBool   pgtype.Bool `json:"value_bool"`
	ValueInt    pgtype.Int4 `json:"value_int"`
	ValueText   pgtype.Text `json:"value_text"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) CreatePlanFeature(ctx context.Context, arg CreatePlanFeatureParams) (PlanFeature, error) {
	row := q.db.QueryRow(ctx, createPlanFeature,
		arg.ID,
		arg.PlanID,
		arg.FeatureKey,
		arg.FeatureType,
		arg.ValueBool,
		arg.ValueInt,
		arg.ValueText,
		arg.CreatedAt,
	)
	var i PlanFeature
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FeatureKey,
		&i.FeatureType,
		&i.ValueBool,
		&i.ValueInt,
		&i.ValueText,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllPlanFeatures = `-- name: DeleteAllPlanFeatures :exec
DELETE FROM plan_features WHERE plan_id = $1
`

func (q *Queries) DeleteAllPlanFeatures(ctx context.Context, planID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllPlanFeatures, planID)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
UPDATE plans SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const deletePlanFeature = `-- name: DeletePlanFeature :exec
DELETE FROM plan_features WHERE plan_id = $1 AND feature_key = $2
`

type DeletePlanFeatureParams struct {
	PlanID     uuid.UUID `json:"plan_id"`
	FeatureKey string    `json:"feature_key"`
}

func (q *Queries) DeletePlanFeature(ctx context.Context, arg DeletePlanFeatureParams) error {
	_, err := q.db.Exec(ctx, deletePlanFeature, arg.PlanID, arg.FeatureKey)
	return err
}

const existsPlanBySlug = `-- name: ExistsPlanBySlug :one
SELECT EXISTS(SELECT 1 FROM plans WHERE slug = $1)
`

func (q *Queries) ExistsPlanBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, existsPlanBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFreePlan = `-- name: GetFreePlan :one
SELECT id, name, slug, description, type, price_monthly, price_yearly, is_trial, trial_days, tier, is_active, created_at, updated_at FROM plans WHERE type = 'free' AND is_active = TRUE ORDER BY tier ASC LIMIT 1
`

func (q *Queries) GetFreePlan(ctx context.Context) (Plan, error) {
	row := q.db.QueryRow(ctx, getFreePlan)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.IsTrial,
		&i.TrialDays,
		&i.Tier,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, slug, description, type, price_monthly, price_yearly, is_trial, trial_days, tier, is_active, created_at, updated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.IsTrial,
		&i.TrialDays,
		&i.Tier,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanBySlug = `-- name: GetPlanBySlug :one
SELECT id, name, slug, description, type, price_monthly, price_yearly, is_trial, trial_days, tier, is_active, created_at, updated_at FROM plans WHERE slug = $1
`

func (q *Queries) GetPlanBySlug(ctx context.Context, slug string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanBySlug, slug)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.IsTrial,
		&i.TrialDays,
		&i.Tier,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanFeatureByKey = `-- name: GetPlanFeatureByKey :one
SELECT id, plan_id, feature_key, feature_type, value_bool, value_int, value_text, created_at FROM plan_features WHERE plan_id = $1 AND feature_key = $2
`

type GetPlanFeatureByKeyParams struct {
	PlanID     uuid.UUID `json:"plan_id"`
	FeatureKey string    `json:"feature_key"`
}

func (q *Queries) GetPlanFeatureByKey(ctx context.Context, arg GetPlanFeatureByKeyParams) (PlanFeature, error) {
	row := q.db.QueryRow(ctx, getPlanFeatureByKey, arg.PlanID, arg.FeatureKey)
	var i PlanFeature
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FeatureKey,
		&i.FeatureType,
		&i.ValueBool,
		&i.ValueInt,
		&i.ValueText,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanFeatures = `-- name: GetPlanFeatures :many
SELECT id, plan_id, feature_key, feature_type, value_bool, value_int, value_text, created_at FROM plan_features WHERE plan_id = $1 ORDER BY feature_key ASC
`

func (q *Queries) GetPlanFeatures(ctx context.Context, planID uuid.UUID) ([]PlanFeature, error) {
	rows, err := q.db.Query(ctx, getPlanFeatures, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanFeature{}
	for rows.Next() {
		var i PlanFeature
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.FeatureKey,
			&i.FeatureType,
			&i.ValueBool,
			&i.ValueInt,
			&i.ValueText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, name, slug, description, type, price_monthly, price_yearly, is_trial, trial_days, tier, is_active, created_at, updated_at FROM plans ORDER BY tier ASC
`

func (q *Queries) ListAllPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.PriceMonthly,
			&i.PriceYearly,
			&i.IsTrial,
			&i.TrialDays,
			&i.Tier,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, slug, description, type, price_monthly, price_yearly, is_trial, trial_days, tier, is_active, created_at, updated_at FROM plans WHERE is_active = TRUE ORDER BY tier ASC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.PriceMonthly,
			&i.PriceYearly,
			&i.IsTrial,
			&i.TrialDays,
			&i.Tier,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans
SET name = $2, slug = $3, description = $4, type = $5, price_monthly = $6, price_yearly = $7,
    is_trial = $8, trial_days = $9, tier = $10, is_active = $11, updated_at = NOW()
WHERE id = $1
`

type UpdatePlanParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  pgtype.Text    `json:"description"`
	Type         string         `json:"type"`
	PriceMonthly pgtype.Numeric `json:"price_monthly"`
	PriceYearly  pgtype.Numeric `json:"price_yearly"`
	IsTrial      bool           `json:"is_trial"`
	TrialDays    int32          `json:"trial_days"`
	Tier         int32          `json:"tier"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.Exec(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Type,
		arg.PriceMonthly,
		arg.PriceYearly,
		arg.IsTrial,
		arg.TrialDays,
		arg.Tier,
		arg.IsActive,
	)
	return err
}

const updatePlanFeature = `-- name: UpdatePlanFeature :exec
UPDATE plan_features
SET feature_type = $3, value_bool = $4, value_int = $5, value_text = $6
WHERE plan_id = $1 AND feature_key = $2
`

type UpdatePlanFeatureParams struct {
	PlanID      uuid.UUID   `json:"plan_id"`
	FeatureKey  string      `json:"feature_key"`
	FeatureType string      `json:"feature_type"`
	ValueBool   pgtype.Bool `json:"value_bool"`
	ValueInt    pgtype.Int4 `json:"value_int"`
	ValueText   pgtype.Text `json:"value_text"`
}

func (q *Queries) UpdatePlanFeature(ctx context.Context, arg UpdatePlanFeatureParams) error {
	_, err := q.db.Exec(ctx, updatePlanFeature,
		arg.PlanID,
		arg.FeatureKey,
		arg.FeatureType,
		arg.ValueBool,
		arg.ValueInt,
		arg.ValueText,
	)
	return err
}

const upsertPlanFeature = `-- name: UpsertPlanFeature :one
INSERT INTO plan_features (id, plan_id, feature_key, feature_type, value_bool, value_int, value_text, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (plan_id, feature_key)
DO UPDATE SET feature_type = EXCLUDED.feature_type, value_bool = EXCLUDED.value_bool, value_int = EXCLUDED.value_int, value_text = EXCLUDED.value_text
RETURNING id, plan_id, feature_key, feature_type, value_bool, value_int, value_text, created_at
`

type UpsertPlanFeatureParams struct {
	ID          uuid.UUID   `json:"id"`
	PlanID      uuid.UUID   `json:"plan_id"`
	FeatureKey  string      `json:"feature_key"`
	FeatureType string      `json:"feature_type"`
	ValueBool   pgtype.Bool `json:"value_bool"`
	ValueInt    pgtype.Int4 `json:"value_int"`
	ValueText   pgtype.Text `json:"value_text"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) UpsertPlanFeature(ctx context.Context, arg UpsertPlanFeatureParams) (PlanFeature, error) {
	row := q.db.QueryRow(ctx, upsertPlanFeature,
		arg.ID,
		arg.PlanID,
		arg.FeatureKey,
		arg.FeatureType,
		arg.ValueBool,
		arg.ValueInt,
		arg.ValueText,
		arg.CreatedAt,
	)
	var i PlanFeature
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FeatureKey,
		&i.FeatureType,
		&i.ValueBool,
		&i.ValueInt,
		&i.ValueText,
		&i.CreatedAt,
	)
	return i, err
}
