// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscription.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE tenant_subscriptions SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelSubscription, id)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO tenant_subscriptions (id, workspace_id, plan_id, status, billing_cycle, started_at, expires_at, trial_ends_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, plan_id, status, billing_cycle, started_at, expires_at, trial_ends_at, cancelled_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID           uuid.UUID   `json:"id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	PlanID       uuid.UUID   `json:"plan_id"`
	Status       string      `json:"status"`
	BillingCycle pgtype.Text `json:"billing_cycle"`
	StartedAt    time.Time   `json:"started_at"`
	ExpiresAt    *time.Time  `json:"expires_at"`
	TrialEndsAt  *time.Time  `json:"trial_ends_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (TenantSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.PlanID,
		arg.Status,
		arg.BillingCycle,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.TrialEndsAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TenantSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireSubscription = `-- name: ExpireSubscription :exec
UPDATE tenant_subscriptions SET status = 'expired', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ExpireSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireSubscription, id)
	return err
}

const expireTrialSubscriptions = `-- name: ExpireTrialSubscriptions :exec
UPDATE tenant_subscriptions SET status = 'expired', updated_at = NOW()
WHERE status = 'trial' AND trial_ends_at < NOW()
`

func (q *Queries) ExpireTrialSubscriptions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireTrialSubscriptions)
	return err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, workspace_id, plan_id, status, billing_cycle, started_at, expires_at, trial_ends_at, cancelled_at, created_at, updated_at FROM tenant_subscriptions
WHERE workspace_id = $1 AND status IN ('active', 'trial')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscription(ctx context.Context, workspaceID uuid.UUID) (TenantSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, workspaceID)
	var i TenantSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, workspace_id, plan_id, status, billing_cycle, started_at, expires_at, trial_ends_at, cancelled_at, created_at, updated_at FROM tenant_subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (TenantSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i TenantSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionWithPlan = `-- name: GetSubscriptionWithPlan :one
SELECT ts.id, ts.workspace_id, ts.plan_id, ts.status, ts.billing_cycle, ts.started_at, ts.expires_at, ts.trial_ends_at, ts.cancelled_at, ts.created_at, ts.updated_at, p.name as plan_name, p.slug as plan_slug, p.type as plan_type, p.tier as plan_tier
FROM tenant_subscriptions ts
JOIN plans p ON ts.plan_id = p.id
WHERE ts.workspace_id = $1 AND ts.status IN ('active', 'trial')
ORDER BY ts.created_at DESC
LIMIT 1
`

type GetSubscriptionWithPlanRow struct {
	ID           uuid.UUID   `json:"id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	PlanID       uuid.UUID   `json:"plan_id"`
	Status       string      `json:"status"`
	BillingCycle pgtype.Text `json:"billing_cycle"`
	StartedAt    time.Time   `json:"started_at"`
	ExpiresAt    *time.Time  `json:"expires_at"`
	TrialEndsAt  *time.Time  `json:"trial_ends_at"`
	CancelledAt  *time.Time  `json:"cancelled_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	PlanName     string      `json:"plan_name"`
	PlanSlug     string      `json:"plan_slug"`
	PlanType     string      `json:"plan_type"`
	PlanTier     int32       `json:"plan_tier"`
}

func (q *Queries) GetSubscriptionWithPlan(ctx context.Context, workspaceID uuid.UUID) (GetSubscriptionWithPlanRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionWithPlan, workspaceID)
	var i GetSubscriptionWithPlanRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
		&i.PlanSlug,
		&i.PlanType,
		&i.PlanTier,
	)
	return i, err
}

const getUsage = `-- name: GetUsage :one
SELECT id, workspace_id, feature_key, usage_count, period_start, period_end, created_at, updated_at FROM tenant_usage
WHERE workspace_id = $1 AND feature_key = $2 AND period_start <= $3 AND period_end > $3
`

type GetUsageParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureKey  string    `json:"feature_key"`
	PeriodStart time.Time `json:"period_start"`
}

func (q *Queries) GetUsage(ctx context.Context, arg GetUsageParams) (TenantUsage, error) {
	row := q.db.QueryRow(ctx, getUsage, arg.WorkspaceID, arg.FeatureKey, arg.PeriodStart)
	var i TenantUsage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureKey,
		&i.UsageCount,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceUsage = `-- name: GetWorkspaceUsage :many
SELECT id, workspace_id, feature_key, usage_count, period_start, period_end, created_at, updated_at FROM tenant_usage
WHERE workspace_id = $1 AND period_start <= $2 AND period_end > $2
ORDER BY feature_key
`

type GetWorkspaceUsageParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	PeriodStart time.Time `json:"period_start"`
}

func (q *Queries) GetWorkspaceUsage(ctx context.Context, arg GetWorkspaceUsageParams) ([]TenantUsage, error) {
	rows, err := q.db.Query(ctx, getWorkspaceUsage, arg.WorkspaceID, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantUsage{}
	for rows.Next() {
		var i TenantUsage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureKey,
			&i.UsageCount,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubscriptions = `-- name: ListAllSubscriptions :many
SELECT ts.id, ts.workspace_id, ts.plan_id, ts.status, ts.billing_cycle, ts.started_at, ts.expires_at, ts.trial_ends_at, ts.cancelled_at, ts.created_at, ts.updated_at, p.name as plan_name, p.slug as plan_slug
FROM tenant_subscriptions ts
JOIN plans p ON ts.plan_id = p.id
ORDER BY ts.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllSubscriptionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllSubscriptionsRow struct {
	ID           uuid.UUID   `json:"id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	PlanID       uuid.UUID   `json:"plan_id"`
	Status       string      `json:"status"`
	BillingCycle pgtype.Text `json:"billing_cycle"`
	StartedAt    time.Time   `json:"started_at"`
	ExpiresAt    *time.Time  `json:"expires_at"`
	TrialEndsAt  *time.Time  `json:"trial_ends_at"`
	CancelledAt  *time.Time  `json:"cancelled_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	PlanName     string      `json:"plan_name"`
	PlanSlug     string      `json:"plan_slug"`
}

func (q *Queries) ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]ListAllSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listAllSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSubscriptionsRow{}
	for rows.Next() {
		var i ListAllSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.TrialEndsAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanName,
			&i.PlanSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByWorkspace = `-- name: ListSubscriptionsByWorkspace :many
SELECT id, workspace_id, plan_id, status, billing_cycle, started_at, expires_at, trial_ends_at, cancelled_at, created_at, updated_at FROM tenant_subscriptions
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]TenantSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSubscription{}
	for rows.Next() {
		var i TenantSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.TrialEndsAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUsage = `-- name: ResetUsage :exec
DELETE FROM tenant_usage WHERE period_end < NOW()
`

func (q *Queries) ResetUsage(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUsage)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE tenant_subscriptions SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.ID, arg.Status)
	return err
}

const upsertUsage = `-- name: UpsertUsage :one
INSERT INTO tenant_usage (id, workspace_id, feature_key, usage_count, period_start, period_end, created_at, updated_at)
VALUES ($1, $2, $3, 1, $4, $5, $6, $7)
ON CONFLICT (workspace_id, feature_key, period_start)
DO UPDATE SET usage_count = tenant_usage.usage_count + 1, updated_at = NOW()
RETURNING id, workspace_id, feature_key, usage_count, period_start, period_end, created_at, updated_at
`

type UpsertUsageParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureKey  string    `json:"feature_key"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpsertUsage(ctx context.Context, arg UpsertUsageParams) (TenantUsage, error) {
	row := q.db.QueryRow(ctx, upsertUsage,
		arg.ID,
		arg.WorkspaceID,
		arg.FeatureKey,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TenantUsage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureKey,
		&i.UsageCount,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
