// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tax.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeTaxReportJob = `-- name: CompleteTaxReportJob :exec
UPDATE tax_report_jobs
SET status = 'COMPLETED', result = $2, completed_at = NOW()
WHERE id = $1 AND workspace_id = $3 AND status = 'PROCESSING'
`

type CompleteTaxReportJobParams struct {
	ID          uuid.UUID `json:"id"`
	Result      []byte    `json:"result"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) CompleteTaxReportJob(ctx context.Context, arg CompleteTaxReportJobParams) error {
	_, err := q.db.Exec(ctx, completeTaxReportJob, arg.ID, arg.Result, arg.WorkspaceID)
	return err
}

const countTaxCalculations = `-- name: CountTaxCalculations :one
SELECT COUNT(*) FROM tax_calculations
WHERE workspace_id = $1
  AND ($2::text IS NULL OR $2::text = '' OR period = $2)
  AND ($3::text IS NULL OR $3::text = '' OR tax_type = $3)
  AND ($4::text IS NULL OR $4::text = '' OR status = $4)
`

type CountTaxCalculationsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Column2     string    `json:"column_2"`
	Column3     string    `json:"column_3"`
	Column4     string    `json:"column_4"`
}

func (q *Queries) CountTaxCalculations(ctx context.Context, arg CountTaxCalculationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTaxCalculations,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTaxCalculation = `-- name: CreateTaxCalculation :one
INSERT INTO tax_calculations (
    id, workspace_id, transaction_id, tax_type, direction,
    base_amount, tax_rate, tax_amount, period, status,
    counterparty_entity_id, faktur_number, metadata, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, workspace_id, transaction_id, tax_type, direction, base_amount, tax_rate, tax_amount, period, status, counterparty_entity_id, faktur_number, metadata, created_at, updated_at
`

type CreateTaxCalculationParams struct {
	ID                   uuid.UUID      `json:"id"`
	WorkspaceID          uuid.UUID      `json:"workspace_id"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	TaxType              string         `json:"tax_type"`
	Direction            string         `json:"direction"`
	BaseAmount           pgtype.Numeric `json:"base_amount"`
	TaxRate              pgtype.Numeric `json:"tax_rate"`
	TaxAmount            pgtype.Numeric `json:"tax_amount"`
	Period               string         `json:"period"`
	Status               string         `json:"status"`
	CounterpartyEntityID pgtype.UUID    `json:"counterparty_entity_id"`
	FakturNumber         pgtype.Text    `json:"faktur_number"`
	Metadata             []byte         `json:"metadata"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTaxCalculation(ctx context.Context, arg CreateTaxCalculationParams) (TaxCalculation, error) {
	row := q.db.QueryRow(ctx, createTaxCalculation,
		arg.ID,
		arg.WorkspaceID,
		arg.TransactionID,
		arg.TaxType,
		arg.Direction,
		arg.BaseAmount,
		arg.TaxRate,
		arg.TaxAmount,
		arg.Period,
		arg.Status,
		arg.CounterpartyEntityID,
		arg.FakturNumber,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TaxCalculation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TransactionID,
		&i.TaxType,
		&i.Direction,
		&i.BaseAmount,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Period,
		&i.Status,
		&i.CounterpartyEntityID,
		&i.FakturNumber,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaxDocumentRef = `-- name: CreateTaxDocumentRef :one
INSERT INTO tax_document_refs (id, tax_calculation_id, document_id, ref_type, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tax_calculation_id, document_id, ref_type, created_at
`

type CreateTaxDocumentRefParams struct {
	ID               uuid.UUID `json:"id"`
	TaxCalculationID uuid.UUID `json:"tax_calculation_id"`
	DocumentID       uuid.UUID `json:"document_id"`
	RefType          string    `json:"ref_type"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) CreateTaxDocumentRef(ctx context.Context, arg CreateTaxDocumentRefParams) (TaxDocumentRef, error) {
	row := q.db.QueryRow(ctx, createTaxDocumentRef,
		arg.ID,
		arg.TaxCalculationID,
		arg.DocumentID,
		arg.RefType,
		arg.CreatedAt,
	)
	var i TaxDocumentRef
	err := row.Scan(
		&i.ID,
		&i.TaxCalculationID,
		&i.DocumentID,
		&i.RefType,
		&i.CreatedAt,
	)
	return i, err
}

const createTaxProfile = `-- name: CreateTaxProfile :one
INSERT INTO tax_profiles (
    id, workspace_id, entity_id, npwp, tax_status, is_ppn_liable,
    default_ppn_rate, pph23_enabled, default_pph23_rate,
    pkp_number, tax_office_code, efaktur_ready, ebupot_ready, notes,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, workspace_id, entity_id, npwp, tax_status, is_ppn_liable, default_ppn_rate, pph23_enabled, default_pph23_rate, pkp_number, tax_office_code, efaktur_ready, ebupot_ready, notes, created_at, updated_at
`

type CreateTaxProfileParams struct {
	ID               uuid.UUID      `json:"id"`
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	EntityID         uuid.UUID      `json:"entity_id"`
	Npwp             pgtype.Text    `json:"npwp"`
	TaxStatus        string         `json:"tax_status"`
	IsPpnLiable      bool           `json:"is_ppn_liable"`
	DefaultPpnRate   pgtype.Numeric `json:"default_ppn_rate"`
	Pph23Enabled     bool           `json:"pph23_enabled"`
	DefaultPph23Rate pgtype.Numeric `json:"default_pph23_rate"`
	PkpNumber        pgtype.Text    `json:"pkp_number"`
	TaxOfficeCode    pgtype.Text    `json:"tax_office_code"`
	EfakturReady     bool           `json:"efaktur_ready"`
	EbupotReady      bool           `json:"ebupot_ready"`
	Notes            pgtype.Text    `json:"notes"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTaxProfile(ctx context.Context, arg CreateTaxProfileParams) (TaxProfile, error) {
	row := q.db.QueryRow(ctx, createTaxProfile,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityID,
		arg.Npwp,
		arg.TaxStatus,
		arg.IsPpnLiable,
		arg.DefaultPpnRate,
		arg.Pph23Enabled,
		arg.DefaultPph23Rate,
		arg.PkpNumber,
		arg.TaxOfficeCode,
		arg.EfakturReady,
		arg.EbupotReady,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TaxProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityID,
		&i.Npwp,
		&i.TaxStatus,
		&i.IsPpnLiable,
		&i.DefaultPpnRate,
		&i.Pph23Enabled,
		&i.DefaultPph23Rate,
		&i.PkpNumber,
		&i.TaxOfficeCode,
		&i.EfakturReady,
		&i.EbupotReady,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaxReportJob = `-- name: CreateTaxReportJob :one
INSERT INTO tax_report_jobs (
    id, workspace_id, report_type, period_from, period_to,
    status, requested_by, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, report_type, period_from, period_to, status, result, error_message, requested_by, created_at, completed_at
`

type CreateTaxReportJobParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ReportType  string    `json:"report_type"`
	PeriodFrom  string    `json:"period_from"`
	PeriodTo    string    `json:"period_to"`
	Status      string    `json:"status"`
	RequestedBy uuid.UUID `json:"requested_by"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateTaxReportJob(ctx context.Context, arg CreateTaxReportJobParams) (TaxReportJob, error) {
	row := q.db.QueryRow(ctx, createTaxReportJob,
		arg.ID,
		arg.WorkspaceID,
		arg.ReportType,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.Status,
		arg.RequestedBy,
		arg.CreatedAt,
	)
	var i TaxReportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReportType,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Status,
		&i.Result,
		&i.ErrorMessage,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failTaxReportJob = `-- name: FailTaxReportJob :exec
UPDATE tax_report_jobs
SET status = 'FAILED', error_message = $2, completed_at = NOW()
WHERE id = $1 AND workspace_id = $3 AND status IN ('PENDING', 'PROCESSING')
`

type FailTaxReportJobParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
}

func (q *Queries) FailTaxReportJob(ctx context.Context, arg FailTaxReportJobParams) error {
	_, err := q.db.Exec(ctx, failTaxReportJob, arg.ID, arg.ErrorMessage, arg.WorkspaceID)
	return err
}

const getPPNSummaryByPeriod = `-- name: GetPPNSummaryByPeriod :one
SELECT
    COALESCE(SUM(CASE WHEN tax_type = 'PPN_MASUKAN' THEN tax_amount ELSE 0 END), 0)::numeric AS ppn_masukan,
    COALESCE(SUM(CASE WHEN tax_type = 'PPN_KELUARAN' THEN tax_amount ELSE 0 END), 0)::numeric AS ppn_keluaran,
    COALESCE(SUM(CASE WHEN tax_type = 'PPN_MASUKAN' THEN base_amount ELSE 0 END), 0)::numeric AS dpp_masukan,
    COALESCE(SUM(CASE WHEN tax_type = 'PPN_KELUARAN' THEN base_amount ELSE 0 END), 0)::numeric AS dpp_keluaran,
    COUNT(*) FILTER (WHERE tax_type IN ('PPN_MASUKAN', 'PPN_KELUARAN'))::bigint AS transaction_count
FROM tax_calculations
WHERE workspace_id = $1
  AND period = $2
  AND status = 'ACTIVE'
`

type GetPPNSummaryByPeriodParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Period      string    `json:"period"`
}

type GetPPNSummaryByPeriodRow struct {
	PpnMasukan       pgtype.Numeric `json:"ppn_masukan"`
	PpnKeluaran      pgtype.Numeric `json:"ppn_keluaran"`
	DppMasukan       pgtype.Numeric `json:"dpp_masukan"`
	DppKeluaran      pgtype.Numeric `json:"dpp_keluaran"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) GetPPNSummaryByPeriod(ctx context.Context, arg GetPPNSummaryByPeriodParams) (GetPPNSummaryByPeriodRow, error) {
	row := q.db.QueryRow(ctx, getPPNSummaryByPeriod, arg.WorkspaceID, arg.Period)
	var i GetPPNSummaryByPeriodRow
	err := row.Scan(
		&i.PpnMasukan,
		&i.PpnKeluaran,
		&i.DppMasukan,
		&i.DppKeluaran,
		&i.TransactionCount,
	)
	return i, err
}

const getPPhSummaryByPeriod = `-- name: GetPPhSummaryByPeriod :many
SELECT
    tax_type,
    direction,
    COALESCE(SUM(base_amount), 0)::numeric AS total_base,
    COALESCE(SUM(tax_amount), 0)::numeric AS total_tax,
    COUNT(*)::bigint AS count
FROM tax_calculations
WHERE workspace_id = $1
  AND period >= $2
  AND period <= $3
  AND tax_type LIKE 'PPH%'
  AND status = 'ACTIVE'
GROUP BY tax_type, direction
ORDER BY tax_type
`

type GetPPhSummaryByPeriodParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Period      string    `json:"period"`
	Period_2    string    `json:"period_2"`
}

type GetPPhSummaryByPeriodRow struct {
	TaxType   string         `json:"tax_type"`
	Direction string         `json:"direction"`
	TotalBase pgtype.Numeric `json:"total_base"`
	TotalTax  pgtype.Numeric `json:"total_tax"`
	Count     int64          `json:"count"`
}

func (q *Queries) GetPPhSummaryByPeriod(ctx context.Context, arg GetPPhSummaryByPeriodParams) ([]GetPPhSummaryByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getPPhSummaryByPeriod, arg.WorkspaceID, arg.Period, arg.Period_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPPhSummaryByPeriodRow{}
	for rows.Next() {
		var i GetPPhSummaryByPeriodRow
		if err := rows.Scan(
			&i.TaxType,
			&i.Direction,
			&i.TotalBase,
			&i.TotalTax,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaxCalculationByID = `-- name: GetTaxCalculationByID :one
SELECT id, workspace_id, transaction_id, tax_type, direction, base_amount, tax_rate, tax_amount, period, status, counterparty_entity_id, faktur_number, metadata, created_at, updated_at FROM tax_calculations WHERE id = $1 AND workspace_id = $2
`

type GetTaxCalculationByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetTaxCalculationByID(ctx context.Context, arg GetTaxCalculationByIDParams) (TaxCalculation, error) {
	row := q.db.QueryRow(ctx, getTaxCalculationByID, arg.ID, arg.WorkspaceID)
	var i TaxCalculation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TransactionID,
		&i.TaxType,
		&i.Direction,
		&i.BaseAmount,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Period,
		&i.Status,
		&i.CounterpartyEntityID,
		&i.FakturNumber,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxCalculationByTransactionAndType = `-- name: GetTaxCalculationByTransactionAndType :one
SELECT id, workspace_id, transaction_id, tax_type, direction, base_amount, tax_rate, tax_amount, period, status, counterparty_entity_id, faktur_number, metadata, created_at, updated_at FROM tax_calculations
WHERE transaction_id = $1 AND tax_type = $2 AND workspace_id = $3
`

type GetTaxCalculationByTransactionAndTypeParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TaxType       string    `json:"tax_type"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetTaxCalculationByTransactionAndType(ctx context.Context, arg GetTaxCalculationByTransactionAndTypeParams) (TaxCalculation, error) {
	row := q.db.QueryRow(ctx, getTaxCalculationByTransactionAndType, arg.TransactionID, arg.TaxType, arg.WorkspaceID)
	var i TaxCalculation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TransactionID,
		&i.TaxType,
		&i.Direction,
		&i.BaseAmount,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Period,
		&i.Status,
		&i.CounterpartyEntityID,
		&i.FakturNumber,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxProfileByWorkspace = `-- name: GetTaxProfileByWorkspace :one
SELECT id, workspace_id, entity_id, npwp, tax_status, is_ppn_liable, default_ppn_rate, pph23_enabled, default_pph23_rate, pkp_number, tax_office_code, efaktur_ready, ebupot_ready, notes, created_at, updated_at FROM tax_profiles WHERE workspace_id = $1
`

func (q *Queries) GetTaxProfileByWorkspace(ctx context.Context, workspaceID uuid.UUID) (TaxProfile, error) {
	row := q.db.QueryRow(ctx, getTaxProfileByWorkspace, workspaceID)
	var i TaxProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityID,
		&i.Npwp,
		&i.TaxStatus,
		&i.IsPpnLiable,
		&i.DefaultPpnRate,
		&i.Pph23Enabled,
		&i.DefaultPph23Rate,
		&i.PkpNumber,
		&i.TaxOfficeCode,
		&i.EfakturReady,
		&i.EbupotReady,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxReportJob = `-- name: GetTaxReportJob :one
SELECT id, workspace_id, report_type, period_from, period_to, status, result, error_message, requested_by, created_at, completed_at FROM tax_report_jobs WHERE id = $1 AND workspace_id = $2
`

type GetTaxReportJobParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetTaxReportJob(ctx context.Context, arg GetTaxReportJobParams) (TaxReportJob, error) {
	row := q.db.QueryRow(ctx, getTaxReportJob, arg.ID, arg.WorkspaceID)
	var i TaxReportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReportType,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Status,
		&i.Result,
		&i.ErrorMessage,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listTaxCalculations = `-- name: ListTaxCalculations :many
SELECT tc.id, tc.workspace_id, tc.transaction_id, tc.tax_type, tc.direction, tc.base_amount, tc.tax_rate, tc.tax_amount, tc.period, tc.status, tc.counterparty_entity_id, tc.faktur_number, tc.metadata, tc.created_at, tc.updated_at, t.transaction_number, t.transaction_type, t.description AS transaction_description
FROM tax_calculations tc
JOIN transactions t ON t.id = tc.transaction_id
WHERE tc.workspace_id = $1
  AND ($2::text IS NULL OR $2::text = '' OR tc.period = $2)
  AND ($3::text IS NULL OR $3::text = '' OR tc.tax_type = $3)
  AND ($4::text IS NULL OR $4::text = '' OR tc.status = $4)
ORDER BY tc.created_at DESC
LIMIT $5 OFFSET $6
`

type ListTaxCalculationsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Column2     string    `json:"column_2"`
	Column3     string    `json:"column_3"`
	Column4     string    `json:"column_4"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListTaxCalculationsRow struct {
	ID                     uuid.UUID      `json:"id"`
	WorkspaceID            uuid.UUID      `json:"workspace_id"`
	TransactionID          uuid.UUID      `json:"transaction_id"`
	TaxType                string         `json:"tax_type"`
	Direction              string         `json:"direction"`
	BaseAmount             pgtype.Numeric `json:"base_amount"`
	TaxRate                pgtype.Numeric `json:"tax_rate"`
	TaxAmount              pgtype.Numeric `json:"tax_amount"`
	Period                 string         `json:"period"`
	Status                 string         `json:"status"`
	CounterpartyEntityID   pgtype.UUID    `json:"counterparty_entity_id"`
	FakturNumber           pgtype.Text    `json:"faktur_number"`
	Metadata               []byte         `json:"metadata"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	TransactionNumber      string         `json:"transaction_number"`
	TransactionType        string         `json:"transaction_type"`
	TransactionDescription pgtype.Text    `json:"transaction_description"`
}

func (q *Queries) ListTaxCalculations(ctx context.Context, arg ListTaxCalculationsParams) ([]ListTaxCalculationsRow, error) {
	rows, err := q.db.Query(ctx, listTaxCalculations,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxCalculationsRow{}
	for rows.Next() {
		var i ListTaxCalculationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TransactionID,
			&i.TaxType,
			&i.Direction,
			&i.BaseAmount,
			&i.TaxRate,
			&i.TaxAmount,
			&i.Period,
			&i.Status,
			&i.CounterpartyEntityID,
			&i.FakturNumber,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionNumber,
			&i.TransactionType,
			&i.TransactionDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxDocumentRefs = `-- name: ListTaxDocumentRefs :many
SELECT tdr.id, tdr.tax_calculation_id, tdr.document_id, tdr.ref_type, tdr.created_at, d.file_name, d.document_type, d.mime_type
FROM tax_document_refs tdr
JOIN documents d ON d.id = tdr.document_id
WHERE tdr.tax_calculation_id = $1
ORDER BY tdr.created_at DESC
`

type ListTaxDocumentRefsRow struct {
	ID               uuid.UUID `json:"id"`
	TaxCalculationID uuid.UUID `json:"tax_calculation_id"`
	DocumentID       uuid.UUID `json:"document_id"`
	RefType          string    `json:"ref_type"`
	CreatedAt        time.Time `json:"created_at"`
	FileName         string    `json:"file_name"`
	DocumentType     string    `json:"document_type"`
	MimeType         string    `json:"mime_type"`
}

func (q *Queries) ListTaxDocumentRefs(ctx context.Context, taxCalculationID uuid.UUID) ([]ListTaxDocumentRefsRow, error) {
	rows, err := q.db.Query(ctx, listTaxDocumentRefs, taxCalculationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxDocumentRefsRow{}
	for rows.Next() {
		var i ListTaxDocumentRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaxCalculationID,
			&i.DocumentID,
			&i.RefType,
			&i.CreatedAt,
			&i.FileName,
			&i.DocumentType,
			&i.MimeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxReportJobs = `-- name: ListTaxReportJobs :many
SELECT id, workspace_id, report_type, period_from, period_to, status, result, error_message, requested_by, created_at, completed_at FROM tax_report_jobs
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTaxReportJobsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListTaxReportJobs(ctx context.Context, arg ListTaxReportJobsParams) ([]TaxReportJob, error) {
	rows, err := q.db.Query(ctx, listTaxReportJobs, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxReportJob{}
	for rows.Next() {
		var i TaxReportJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReportType,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Status,
			&i.Result,
			&i.ErrorMessage,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaxProfile = `-- name: UpdateTaxProfile :one
UPDATE tax_profiles SET
    npwp = $2,
    tax_status = $3,
    is_ppn_liable = $4,
    default_ppn_rate = $5,
    pph23_enabled = $6,
    default_pph23_rate = $7,
    pkp_number = $8,
    tax_office_code = $9,
    efaktur_ready = $10,
    ebupot_ready = $11,
    notes = $12,
    updated_at = NOW()
WHERE workspace_id = $1
RETURNING id, workspace_id, entity_id, npwp, tax_status, is_ppn_liable, default_ppn_rate, pph23_enabled, default_pph23_rate, pkp_number, tax_office_code, efaktur_ready, ebupot_ready, notes, created_at, updated_at
`

type UpdateTaxProfileParams struct {
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	Npwp             pgtype.Text    `json:"npwp"`
	TaxStatus        string         `json:"tax_status"`
	IsPpnLiable      bool           `json:"is_ppn_liable"`
	DefaultPpnRate   pgtype.Numeric `json:"default_ppn_rate"`
	Pph23Enabled     bool           `json:"pph23_enabled"`
	DefaultPph23Rate pgtype.Numeric `json:"default_pph23_rate"`
	PkpNumber        pgtype.Text    `json:"pkp_number"`
	TaxOfficeCode    pgtype.Text    `json:"tax_office_code"`
	EfakturReady     bool           `json:"efaktur_ready"`
	EbupotReady      bool           `json:"ebupot_ready"`
	Notes            pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateTaxProfile(ctx context.Context, arg UpdateTaxProfileParams) (TaxProfile, error) {
	row := q.db.QueryRow(ctx, updateTaxProfile,
		arg.WorkspaceID,
		arg.Npwp,
		arg.TaxStatus,
		arg.IsPpnLiable,
		arg.DefaultPpnRate,
		arg.Pph23Enabled,
		arg.DefaultPph23Rate,
		arg.PkpNumber,
		arg.TaxOfficeCode,
		arg.EfakturReady,
		arg.EbupotReady,
		arg.Notes,
	)
	var i TaxProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityID,
		&i.Npwp,
		&i.TaxStatus,
		&i.IsPpnLiable,
		&i.DefaultPpnRate,
		&i.Pph23Enabled,
		&i.DefaultPph23Rate,
		&i.PkpNumber,
		&i.TaxOfficeCode,
		&i.EfakturReady,
		&i.EbupotReady,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaxReportJobProcessing = `-- name: UpdateTaxReportJobProcessing :one
UPDATE tax_report_jobs
SET status = 'PROCESSING'
WHERE id = $1 AND workspace_id = $2 AND status = 'PENDING'
RETURNING id
`

type UpdateTaxReportJobProcessingParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateTaxReportJobProcessing(ctx context.Context, arg UpdateTaxReportJobProcessingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateTaxReportJobProcessing, arg.ID, arg.WorkspaceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const voidTaxCalculationsByTransaction = `-- name: VoidTaxCalculationsByTransaction :exec
UPDATE tax_calculations
SET status = 'VOIDED', updated_at = NOW()
WHERE transaction_id = $1 AND workspace_id = $2 AND status = 'ACTIVE'
`

type VoidTaxCalculationsByTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

func (q *Queries) VoidTaxCalculationsByTransaction(ctx context.Context, arg VoidTaxCalculationsByTransactionParams) error {
	_, err := q.db.Exec(ctx, voidTaxCalculationsByTransaction, arg.TransactionID, arg.WorkspaceID)
	return err
}
