// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRelation = `-- name: CreateRelation :one
INSERT INTO entity_relations (id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at
`

type CreateRelationParams struct {
	ID           uuid.UUID   `json:"id"`
	ObjectID     uuid.UUID   `json:"object_id"`
	SubjectID    uuid.UUID   `json:"subject_id"`
	RelationType string      `json:"relation_type"`
	CustomAlias  pgtype.Text `json:"custom_alias"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateRelation(ctx context.Context, arg CreateRelationParams) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, createRelation,
		arg.ID,
		arg.ObjectID,
		arg.SubjectID,
		arg.RelationType,
		arg.CustomAlias,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoleAssignment = `-- name: CreateRoleAssignment :one

INSERT INTO workspace_role_assignments (id, workspace_id, member_entity_id, role_id, assigned_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, member_entity_id, role_id, assigned_by, created_at
`

type CreateRoleAssignmentParams struct {
	ID             uuid.UUID `json:"id"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
	RoleID         uuid.UUID `json:"role_id"`
	AssignedBy     uuid.UUID `json:"assigned_by"`
	CreatedAt      time.Time `json:"created_at"`
}

// ============================================================
// Workspace Role Assignments
// ============================================================
func (q *Queries) CreateRoleAssignment(ctx context.Context, arg CreateRoleAssignmentParams) (WorkspaceRoleAssignment, error) {
	row := q.db.QueryRow(ctx, createRoleAssignment,
		arg.ID,
		arg.WorkspaceID,
		arg.MemberEntityID,
		arg.RoleID,
		arg.AssignedBy,
		arg.CreatedAt,
	)
	var i WorkspaceRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MemberEntityID,
		&i.RoleID,
		&i.AssignedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceRole = `-- name: CreateWorkspaceRole :one

INSERT INTO workspace_roles (id, workspace_id, name, description, permissions, is_system, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, name, description, permissions, is_system, created_by, created_at, updated_at
`

type CreateWorkspaceRoleParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Permissions []string    `json:"permissions"`
	IsSystem    bool        `json:"is_system"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

// ============================================================
// Workspace Roles (ABAC)
// ============================================================
func (q *Queries) CreateWorkspaceRole(ctx context.Context, arg CreateWorkspaceRoleParams) (WorkspaceRole, error) {
	row := q.db.QueryRow(ctx, createWorkspaceRole,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.IsSystem,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkspaceRole
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllRoleAssignmentsForMember = `-- name: DeleteAllRoleAssignmentsForMember :exec
DELETE FROM workspace_role_assignments
WHERE workspace_id = $1 AND member_entity_id = $2
`

type DeleteAllRoleAssignmentsForMemberParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
}

func (q *Queries) DeleteAllRoleAssignmentsForMember(ctx context.Context, arg DeleteAllRoleAssignmentsForMemberParams) error {
	_, err := q.db.Exec(ctx, deleteAllRoleAssignmentsForMember, arg.WorkspaceID, arg.MemberEntityID)
	return err
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM entity_relations WHERE id = $1
`

func (q *Queries) DeleteRelation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelation, id)
	return err
}

const deleteRoleAssignment = `-- name: DeleteRoleAssignment :exec
DELETE FROM workspace_role_assignments
WHERE workspace_id = $1 AND member_entity_id = $2 AND role_id = $3
`

type DeleteRoleAssignmentParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
	RoleID         uuid.UUID `json:"role_id"`
}

func (q *Queries) DeleteRoleAssignment(ctx context.Context, arg DeleteRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteRoleAssignment, arg.WorkspaceID, arg.MemberEntityID, arg.RoleID)
	return err
}

const deleteWorkspaceRole = `-- name: DeleteWorkspaceRole :exec
DELETE FROM workspace_roles WHERE id = $1 AND is_system = FALSE
`

func (q *Queries) DeleteWorkspaceRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceRole, id)
	return err
}

const existsCounterpartyRelation = `-- name: ExistsCounterpartyRelation :one
SELECT EXISTS(
    SELECT 1 FROM entity_relations
    WHERE object_id = $1 AND subject_id = $2
      AND relation_type IN ('PELANGGAN', 'VENDOR') AND status = 'ACTIVE'
)
`

type ExistsCounterpartyRelationParams struct {
	ObjectID  uuid.UUID `json:"object_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) ExistsCounterpartyRelation(ctx context.Context, arg ExistsCounterpartyRelationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCounterpartyRelation, arg.ObjectID, arg.SubjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsRelation = `-- name: ExistsRelation :one
SELECT EXISTS(
    SELECT 1 FROM entity_relations
    WHERE object_id = $1 AND subject_id = $2 AND relation_type = $3
)
`

type ExistsRelationParams struct {
	ObjectID     uuid.UUID `json:"object_id"`
	SubjectID    uuid.UUID `json:"subject_id"`
	RelationType string    `json:"relation_type"`
}

func (q *Queries) ExistsRelation(ctx context.Context, arg ExistsRelationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsRelation, arg.ObjectID, arg.SubjectID, arg.RelationType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getMemberPermissions = `-- name: GetMemberPermissions :many
SELECT DISTINCT unnest(wr.permissions) as permission
FROM workspace_role_assignments wra
JOIN workspace_roles wr ON wra.role_id = wr.id
WHERE wra.workspace_id = $1 AND wra.member_entity_id = $2
`

type GetMemberPermissionsParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
}

func (q *Queries) GetMemberPermissions(ctx context.Context, arg GetMemberPermissionsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getMemberPermissions, arg.WorkspaceID, arg.MemberEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var permission interface{}
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelation = `-- name: GetRelation :one
SELECT id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at FROM entity_relations
WHERE object_id = $1 AND subject_id = $2 AND relation_type = $3
`

type GetRelationParams struct {
	ObjectID     uuid.UUID `json:"object_id"`
	SubjectID    uuid.UUID `json:"subject_id"`
	RelationType string    `json:"relation_type"`
}

func (q *Queries) GetRelation(ctx context.Context, arg GetRelationParams) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, getRelation, arg.ObjectID, arg.SubjectID, arg.RelationType)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelationByID = `-- name: GetRelationByID :one
SELECT id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at FROM entity_relations WHERE id = $1
`

func (q *Queries) GetRelationByID(ctx context.Context, id uuid.UUID) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, getRelationByID, id)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleAssignment = `-- name: GetRoleAssignment :one
SELECT id, workspace_id, member_entity_id, role_id, assigned_by, created_at FROM workspace_role_assignments
WHERE workspace_id = $1 AND member_entity_id = $2 AND role_id = $3
`

type GetRoleAssignmentParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
	RoleID         uuid.UUID `json:"role_id"`
}

func (q *Queries) GetRoleAssignment(ctx context.Context, arg GetRoleAssignmentParams) (WorkspaceRoleAssignment, error) {
	row := q.db.QueryRow(ctx, getRoleAssignment, arg.WorkspaceID, arg.MemberEntityID, arg.RoleID)
	var i WorkspaceRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MemberEntityID,
		&i.RoleID,
		&i.AssignedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWorkspaceAccess = `-- name: GetUserWorkspaceAccess :one
SELECT er.id, er.object_id, er.subject_id, er.relation_type, er.custom_alias, er.status, er.created_at, er.updated_at
FROM entity_relations er
WHERE er.object_id = $1 AND er.subject_id = $2 AND er.status = 'ACTIVE'
AND er.relation_type IN ('PEMILIK', 'KARYAWAN')
LIMIT 1
`

type GetUserWorkspaceAccessParams struct {
	ObjectID  uuid.UUID `json:"object_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) GetUserWorkspaceAccess(ctx context.Context, arg GetUserWorkspaceAccessParams) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, getUserWorkspaceAccess, arg.ObjectID, arg.SubjectID)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceRoleByID = `-- name: GetWorkspaceRoleByID :one
SELECT id, workspace_id, name, description, permissions, is_system, created_by, created_at, updated_at FROM workspace_roles WHERE id = $1
`

func (q *Queries) GetWorkspaceRoleByID(ctx context.Context, id uuid.UUID) (WorkspaceRole, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleByID, id)
	var i WorkspaceRole
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceRoleByName = `-- name: GetWorkspaceRoleByName :one
SELECT id, workspace_id, name, description, permissions, is_system, created_by, created_at, updated_at FROM workspace_roles WHERE workspace_id = $1 AND name = $2
`

type GetWorkspaceRoleByNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

func (q *Queries) GetWorkspaceRoleByName(ctx context.Context, arg GetWorkspaceRoleByNameParams) (WorkspaceRole, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleByName, arg.WorkspaceID, arg.Name)
	var i WorkspaceRole
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCounterpartyAliasesFromRelations = `-- name: ListCounterpartyAliasesFromRelations :many
SELECT er.id, er.object_id as workspace_id, er.subject_id as entity_id,
       e.nama_utama as entity_name, er.custom_alias, er.created_at
FROM entity_relations er
JOIN entities e ON e.id = er.subject_id
WHERE er.object_id = $1
  AND er.relation_type IN ('PELANGGAN', 'VENDOR')
  AND er.status = 'ACTIVE'
  AND er.custom_alias IS NOT NULL
ORDER BY er.custom_alias ASC
`

type ListCounterpartyAliasesFromRelationsRow struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	EntityID    uuid.UUID   `json:"entity_id"`
	EntityName  string      `json:"entity_name"`
	CustomAlias pgtype.Text `json:"custom_alias"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListCounterpartyAliasesFromRelations(ctx context.Context, objectID uuid.UUID) ([]ListCounterpartyAliasesFromRelationsRow, error) {
	rows, err := q.db.Query(ctx, listCounterpartyAliasesFromRelations, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterpartyAliasesFromRelationsRow{}
	for rows.Next() {
		var i ListCounterpartyAliasesFromRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityID,
			&i.EntityName,
			&i.CustomAlias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByObject = `-- name: ListRelationsByObject :many
SELECT id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at FROM entity_relations
WHERE object_id = $1 AND status = 'ACTIVE'
ORDER BY relation_type, created_at DESC
`

func (q *Queries) ListRelationsByObject(ctx context.Context, objectID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsByObject, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByObjectAndType = `-- name: ListRelationsByObjectAndType :many
SELECT id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at FROM entity_relations
WHERE object_id = $1 AND relation_type = $2 AND status = 'ACTIVE'
ORDER BY created_at DESC
`

type ListRelationsByObjectAndTypeParams struct {
	ObjectID     uuid.UUID `json:"object_id"`
	RelationType string    `json:"relation_type"`
}

func (q *Queries) ListRelationsByObjectAndType(ctx context.Context, arg ListRelationsByObjectAndTypeParams) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsByObjectAndType, arg.ObjectID, arg.RelationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsBySubject = `-- name: ListRelationsBySubject :many
SELECT id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at FROM entity_relations
WHERE subject_id = $1 AND status = 'ACTIVE'
ORDER BY created_at DESC
`

func (q *Queries) ListRelationsBySubject(ctx context.Context, subjectID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleAssignmentsByMember = `-- name: ListRoleAssignmentsByMember :many
SELECT wra.id, wra.workspace_id, wra.member_entity_id, wra.role_id, wra.assigned_by, wra.created_at, wr.name as role_name, wr.permissions as role_permissions
FROM workspace_role_assignments wra
JOIN workspace_roles wr ON wra.role_id = wr.id
WHERE wra.workspace_id = $1 AND wra.member_entity_id = $2
`

type ListRoleAssignmentsByMemberParams struct {
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	MemberEntityID uuid.UUID `json:"member_entity_id"`
}

type ListRoleAssignmentsByMemberRow struct {
	ID              uuid.UUID `json:"id"`
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	MemberEntityID  uuid.UUID `json:"member_entity_id"`
	RoleID          uuid.UUID `json:"role_id"`
	AssignedBy      uuid.UUID `json:"assigned_by"`
	CreatedAt       time.Time `json:"created_at"`
	RoleName        string    `json:"role_name"`
	RolePermissions []string  `json:"role_permissions"`
}

func (q *Queries) ListRoleAssignmentsByMember(ctx context.Context, arg ListRoleAssignmentsByMemberParams) ([]ListRoleAssignmentsByMemberRow, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentsByMember, arg.WorkspaceID, arg.MemberEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleAssignmentsByMemberRow{}
	for rows.Next() {
		var i ListRoleAssignmentsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.MemberEntityID,
			&i.RoleID,
			&i.AssignedBy,
			&i.CreatedAt,
			&i.RoleName,
			&i.RolePermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleAssignmentsByWorkspace = `-- name: ListRoleAssignmentsByWorkspace :many
SELECT wra.id, wra.workspace_id, wra.member_entity_id, wra.role_id, wra.assigned_by, wra.created_at, wr.name as role_name, wr.permissions as role_permissions
FROM workspace_role_assignments wra
JOIN workspace_roles wr ON wra.role_id = wr.id
WHERE wra.workspace_id = $1
ORDER BY wra.created_at DESC
`

type ListRoleAssignmentsByWorkspaceRow struct {
	ID              uuid.UUID `json:"id"`
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	MemberEntityID  uuid.UUID `json:"member_entity_id"`
	RoleID          uuid.UUID `json:"role_id"`
	AssignedBy      uuid.UUID `json:"assigned_by"`
	CreatedAt       time.Time `json:"created_at"`
	RoleName        string    `json:"role_name"`
	RolePermissions []string  `json:"role_permissions"`
}

func (q *Queries) ListRoleAssignmentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListRoleAssignmentsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleAssignmentsByWorkspaceRow{}
	for rows.Next() {
		var i ListRoleAssignmentsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.MemberEntityID,
			&i.RoleID,
			&i.AssignedBy,
			&i.CreatedAt,
			&i.RoleName,
			&i.RolePermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceRoles = `-- name: ListWorkspaceRoles :many
SELECT id, workspace_id, name, description, permissions, is_system, created_by, created_at, updated_at FROM workspace_roles WHERE workspace_id = $1 ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListWorkspaceRoles(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceRole, error) {
	rows, err := q.db.Query(ctx, listWorkspaceRoles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceRole{}
	for rows.Next() {
		var i WorkspaceRole
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsSystem,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesBySubject = `-- name: ListWorkspacesBySubject :many
SELECT id, object_id, subject_id, relation_type, custom_alias, status, created_at, updated_at FROM entity_relations
WHERE subject_id = $1 AND relation_type IN ('PEMILIK', 'KARYAWAN') AND status = 'ACTIVE'
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesBySubject(ctx context.Context, subjectID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listWorkspacesBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounterpartyRelationAlias = `-- name: UpdateCounterpartyRelationAlias :exec
UPDATE entity_relations
SET custom_alias = $3, updated_at = NOW()
WHERE object_id = $1 AND subject_id = $2
  AND relation_type IN ('PELANGGAN', 'VENDOR') AND status = 'ACTIVE'
`

type UpdateCounterpartyRelationAliasParams struct {
	ObjectID    uuid.UUID   `json:"object_id"`
	SubjectID   uuid.UUID   `json:"subject_id"`
	CustomAlias pgtype.Text `json:"custom_alias"`
}

func (q *Queries) UpdateCounterpartyRelationAlias(ctx context.Context, arg UpdateCounterpartyRelationAliasParams) error {
	_, err := q.db.Exec(ctx, updateCounterpartyRelationAlias, arg.ObjectID, arg.SubjectID, arg.CustomAlias)
	return err
}

const updateRelation = `-- name: UpdateRelation :exec
UPDATE entity_relations
SET custom_alias = $2, status = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateRelationParams struct {
	ID          uuid.UUID   `json:"id"`
	CustomAlias pgtype.Text `json:"custom_alias"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateRelation(ctx context.Context, arg UpdateRelationParams) error {
	_, err := q.db.Exec(ctx, updateRelation, arg.ID, arg.CustomAlias, arg.Status)
	return err
}

const updateRelationStatus = `-- name: UpdateRelationStatus :exec
UPDATE entity_relations SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateRelationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateRelationStatus(ctx context.Context, arg UpdateRelationStatusParams) error {
	_, err := q.db.Exec(ctx, updateRelationStatus, arg.ID, arg.Status)
	return err
}

const updateWorkspaceRole = `-- name: UpdateWorkspaceRole :exec
UPDATE workspace_roles
SET name = $2, description = $3, permissions = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateWorkspaceRoleParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Permissions []string    `json:"permissions"`
}

func (q *Queries) UpdateWorkspaceRole(ctx context.Context, arg UpdateWorkspaceRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Permissions,
	)
	return err
}
