// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRelation = `-- name: CreateRelation :one
INSERT INTO entity_relations (id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at
`

type CreateRelationParams struct {
	ID           uuid.UUID   `json:"id"`
	ObjectID     uuid.UUID   `json:"object_id"`
	SubjectID    uuid.UUID   `json:"subject_id"`
	RelationType string      `json:"relation_type"`
	CustomAlias  pgtype.Text `json:"custom_alias"`
	RoleID       pgtype.UUID `json:"role_id"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateRelation(ctx context.Context, arg CreateRelationParams) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, createRelation,
		arg.ID,
		arg.ObjectID,
		arg.SubjectID,
		arg.RelationType,
		arg.CustomAlias,
		arg.RoleID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM entity_relations WHERE id = $1
`

func (q *Queries) DeleteRelation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelation, id)
	return err
}

const existsRelation = `-- name: ExistsRelation :one
SELECT EXISTS(
    SELECT 1 FROM entity_relations
    WHERE object_id = $1 AND subject_id = $2 AND relation_type = $3
)
`

type ExistsRelationParams struct {
	ObjectID     uuid.UUID `json:"object_id"`
	SubjectID    uuid.UUID `json:"subject_id"`
	RelationType string    `json:"relation_type"`
}

func (q *Queries) ExistsRelation(ctx context.Context, arg ExistsRelationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsRelation, arg.ObjectID, arg.SubjectID, arg.RelationType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRelation = `-- name: GetRelation :one
SELECT id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at FROM entity_relations
WHERE object_id = $1 AND subject_id = $2 AND relation_type = $3
`

type GetRelationParams struct {
	ObjectID     uuid.UUID `json:"object_id"`
	SubjectID    uuid.UUID `json:"subject_id"`
	RelationType string    `json:"relation_type"`
}

func (q *Queries) GetRelation(ctx context.Context, arg GetRelationParams) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, getRelation, arg.ObjectID, arg.SubjectID, arg.RelationType)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelationByID = `-- name: GetRelationByID :one
SELECT id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at FROM entity_relations WHERE id = $1
`

func (q *Queries) GetRelationByID(ctx context.Context, id uuid.UUID) (EntityRelation, error) {
	row := q.db.QueryRow(ctx, getRelationByID, id)
	var i EntityRelation
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, permissions, created_at FROM master_roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (MasterRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i MasterRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, permissions, created_at FROM master_roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (MasterRole, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i MasterRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWorkspaceRole = `-- name: GetUserWorkspaceRole :one
SELECT er.id, er.object_id, er.subject_id, er.relation_type, er.custom_alias, er.role_id, er.status, er.created_at, er.updated_at, mr.name as role_name, mr.permissions as role_permissions
FROM entity_relations er
LEFT JOIN master_roles mr ON er.role_id = mr.id
WHERE er.object_id = $1 AND er.subject_id = $2 AND er.status = 'ACTIVE'
AND er.relation_type IN ('PEMILIK', 'KARYAWAN')
LIMIT 1
`

type GetUserWorkspaceRoleParams struct {
	ObjectID  uuid.UUID `json:"object_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type GetUserWorkspaceRoleRow struct {
	ID              uuid.UUID   `json:"id"`
	ObjectID        uuid.UUID   `json:"object_id"`
	SubjectID       uuid.UUID   `json:"subject_id"`
	RelationType    string      `json:"relation_type"`
	CustomAlias     pgtype.Text `json:"custom_alias"`
	RoleID          pgtype.UUID `json:"role_id"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	RoleName        pgtype.Text `json:"role_name"`
	RolePermissions []byte      `json:"role_permissions"`
}

func (q *Queries) GetUserWorkspaceRole(ctx context.Context, arg GetUserWorkspaceRoleParams) (GetUserWorkspaceRoleRow, error) {
	row := q.db.QueryRow(ctx, getUserWorkspaceRole, arg.ObjectID, arg.SubjectID)
	var i GetUserWorkspaceRoleRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.SubjectID,
		&i.RelationType,
		&i.CustomAlias,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RolePermissions,
	)
	return i, err
}

const listRelationsByObject = `-- name: ListRelationsByObject :many
SELECT id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at FROM entity_relations
WHERE object_id = $1 AND status = 'ACTIVE'
ORDER BY relation_type, created_at DESC
`

func (q *Queries) ListRelationsByObject(ctx context.Context, objectID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsByObject, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.RoleID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByObjectAndType = `-- name: ListRelationsByObjectAndType :many
SELECT id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at FROM entity_relations
WHERE object_id = $1 AND relation_type = $2 AND status = 'ACTIVE'
ORDER BY created_at DESC
`

type ListRelationsByObjectAndTypeParams struct {
	ObjectID     uuid.UUID `json:"object_id"`
	RelationType string    `json:"relation_type"`
}

func (q *Queries) ListRelationsByObjectAndType(ctx context.Context, arg ListRelationsByObjectAndTypeParams) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsByObjectAndType, arg.ObjectID, arg.RelationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.RoleID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsBySubject = `-- name: ListRelationsBySubject :many
SELECT id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at FROM entity_relations
WHERE subject_id = $1 AND status = 'ACTIVE'
ORDER BY created_at DESC
`

func (q *Queries) ListRelationsBySubject(ctx context.Context, subjectID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.RoleID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, permissions, created_at FROM master_roles ORDER BY name ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]MasterRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterRole{}
	for rows.Next() {
		var i MasterRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesBySubject = `-- name: ListWorkspacesBySubject :many
SELECT id, object_id, subject_id, relation_type, custom_alias, role_id, status, created_at, updated_at FROM entity_relations
WHERE subject_id = $1 AND relation_type IN ('PEMILIK', 'KARYAWAN') AND status = 'ACTIVE'
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesBySubject(ctx context.Context, subjectID uuid.UUID) ([]EntityRelation, error) {
	rows, err := q.db.Query(ctx, listWorkspacesBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRelation{}
	for rows.Next() {
		var i EntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.SubjectID,
			&i.RelationType,
			&i.CustomAlias,
			&i.RoleID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelation = `-- name: UpdateRelation :exec
UPDATE entity_relations
SET custom_alias = $2, role_id = $3, status = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateRelationParams struct {
	ID          uuid.UUID   `json:"id"`
	CustomAlias pgtype.Text `json:"custom_alias"`
	RoleID      pgtype.UUID `json:"role_id"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateRelation(ctx context.Context, arg UpdateRelationParams) error {
	_, err := q.db.Exec(ctx, updateRelation,
		arg.ID,
		arg.CustomAlias,
		arg.RoleID,
		arg.Status,
	)
	return err
}

const updateRelationStatus = `-- name: UpdateRelationStatus :exec
UPDATE entity_relations SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateRelationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateRelationStatus(ctx context.Context, arg UpdateRelationStatusParams) error {
	_, err := q.db.Exec(ctx, updateRelationStatus, arg.ID, arg.Status)
	return err
}
